insert into KLUB (id,  Ime, Naslov) values (1501, 'Heathcote, Hoppe and Gleichner', '3 Hansons Alley');
insert into KLUB (id,  Ime, Naslov) values (1502, 'Mohr Inc', '6 8th Plaza');
insert into KLUB (id,  Ime, Naslov) values (1503, 'Macejkovic Group', '50 Thompson Street');
insert into KLUB (id,  Ime, Naslov) values (1504, 'Konopelski Haley and Franecki', '55 Hauk Street');
insert into KLUB (id,  Ime, Naslov) values (1505, 'Maggio and Sons', '4 Westport Avenue');
insert into KLUB (id,  Ime, Naslov) values (1506, 'Sawayn LLC', '7 Spaight Road');
insert into KLUB (id,  Ime, Naslov) values (1507, 'Hayes Vandervort and Daniel', '5 Welch Avenue');
insert into KLUB (id,  Ime, Naslov) values (1508, 'Goyette Sporer and Bergnaum', '76 Ronald Regan Place');
insert into KLUB (id,  Ime, Naslov) values (1509, 'Hoppe and Sons', '288 John Wall Place');
insert into KLUB (id,  Ime, Naslov) values (1510, 'Torphy-Lemke', '840 Dayton Terrace');
insert into KLUB (id,  Ime, Naslov) values (1511, 'Gibson, Gottlieb and Keebler', '49839 Onsgard Park');
insert into KLUB (id,  Ime, Naslov) values (1512, 'Gutkowski LLC', '80 Continental Crossing');
insert into KLUB (id,  Ime, Naslov) values (1513, 'Armstrong Inc', '92 Dapin Hill');
insert into KLUB (id,  Ime, Naslov) values (1514, 'D''Amore Lebsack and Jerde', '555 Fallview Park');
insert into KLUB (id,  Ime, Naslov) values (1515, 'Lindgren Huel and Wiza', '70937 Lawn Hill');
insert into KLUB (id,  Ime, Naslov) values (1516, 'Hilpert LLC', '44 Westerfield Avenue');
insert into KLUB (id,  Ime, Naslov) values (1517, 'Legros, Watsica and Mills', '5 Pierstorff Court');
insert into KLUB (id,  Ime, Naslov) values (1518, 'Olson Group', '7255 Manley Circle');
insert into KLUB (id,  Ime, Naslov) values (1519, 'Metz Inc', '3 Buhler Street');
insert into KLUB (id,  Ime, Naslov) values (1520, 'Adams, Lueilwitz and Kihn', '61047 Heffernan Center');
insert into KLUB (id,  Ime, Naslov) values (1521, 'Murazik LLC', '942 Stuart Crossing');
insert into KLUB (id,  Ime, Naslov) values (1522, 'Ward, Gutkowski and Hansen', '470 Sloan Avenue');
insert into KLUB (id,  Ime, Naslov) values (1523, 'Barrows, Rowe and Christiansen', '21025 4th Alley');
insert into KLUB (id,  Ime, Naslov) values (1524, 'DuBuque, Reinger and D''Amore', '28154 Maryland Hill');
insert into KLUB (id,  Ime, Naslov) values (1525, 'Klein and Sons', '0 Waxwing Parkway');
insert into KLUB (id,  Ime, Naslov) values (1526, 'Gutmann, Gaylord and Pfannerstill', '9148 Prentice Way');
insert into KLUB (id,  Ime, Naslov) values (1527, 'Pfeffer-Mohr', '11 Forest Street');
insert into KLUB (id,  Ime, Naslov) values (1528, 'Johns-Rippin', '66 Kennedy Plaza');
insert into KLUB (id,  Ime, Naslov) values (1529, 'Berge Inc', '5574 John Wall Park');
insert into KLUB (id,  Ime, Naslov) values (1530, 'Gislason Schuppe and McGlynn', '71 Muir Court');
insert into KLUB (id,  Ime, Naslov) values (1531, 'Zboncak Group', '2119 Elmside Alley');
insert into KLUB (id,  Ime, Naslov) values (1532, 'Hermann Will and Effertz', '42774 Meadow Ridge Crossing');
insert into KLUB (id,  Ime, Naslov) values (1533, 'Flatley-Schaefer', '059 3rd Point');
insert into KLUB (id,  Ime, Naslov) values (1534, 'Rolfson, Yost and Kshlerin', '5 Spenser Circle');
insert into KLUB (id,  Ime, Naslov) values (1535, 'Muller Group', '32601 Delladonna Park');
insert into KLUB (id,  Ime, Naslov) values (1536, 'Jakubowski and Sons', '7785 Vernon Point');
insert into KLUB (id,  Ime, Naslov) values (1537, 'Boyer Torp and Satterfield', '56609 Old Gate Drive');
insert into KLUB (id,  Ime, Naslov) values (1538, 'Vandervort and Sons', '23 Elmside Way');
insert into KLUB (id,  Ime, Naslov) values (1539, 'Sawayn and Sons', '9 Graceland Plaza');
insert into KLUB (id,  Ime, Naslov) values (1540, 'Spinka Hermann and O''Conner', '6162 Esker Park');
insert into KLUB (id,  Ime, Naslov) values (1541, 'Jaskolski Inc', '61767 Porter Terrace');
insert into KLUB (id,  Ime, Naslov) values (1542, 'Beer Inc', '446 Schurz Drive');
insert into KLUB (id,  Ime, Naslov) values (1543, 'Dibbert Sipes and Anderson', '104 Karstens Crossing');
insert into KLUB (id,  Ime, Naslov) values (1544, 'Rippin-Altenwerth', '3 Mockingbird Place');
insert into KLUB (id,  Ime, Naslov) values (1545, 'Miller Toy and Harber', '0 Eastwood Terrace');
insert into KLUB (id,  Ime, Naslov) values (1546, 'Dickens Sanford and Considine', '44083 Badeau Road');
insert into KLUB (id,  Ime, Naslov) values (1547, 'Ebert LLC', '13 Russell Road');
insert into KLUB (id,  Ime, Naslov) values (1548, 'Fadel Bashirian and Hackett', '4681 2nd Court');
insert into KLUB (id,  Ime, Naslov) values (1549, 'Yundt-Bartell', '15 Pawling Park');
insert into KLUB (id,  Ime, Naslov) values (1550, 'Mueller LLC', '4293 Talmadge Junction');
insert into KLUB (id,  Ime, Naslov) values (1551, 'Smith and Sons', '833 Burrows Road');
insert into KLUB (id,  Ime, Naslov) values (1552, 'Lubowitz Inc', '823 Melody Plaza');
insert into KLUB (id,  Ime, Naslov) values (1553, 'Stoltenberg LLC', '0815 Esker Plaza');
insert into KLUB (id,  Ime, Naslov) values (1554, 'Wehner-Brekke', '30822 Kropf Place');
insert into KLUB (id,  Ime, Naslov) values (1555, 'Collins Group', '68 Transport Parkway');
insert into KLUB (id,  Ime, Naslov) values (1556, 'Lehner-Champlin', '67616 Bluestem Junction');
insert into KLUB (id,  Ime, Naslov) values (1557, 'Stracke Group', '07929 South Street');
insert into KLUB (id,  Ime, Naslov) values (1558, 'Sporer Inc', '1 Canary Avenue');
insert into KLUB (id,  Ime, Naslov) values (1559, 'Murphy LLC', '874 Trailsway Pass');
insert into KLUB (id,  Ime, Naslov) values (1560, 'Upton LLC', '15636 Tomscot Park');
insert into KLUB (id,  Ime, Naslov) values (1561, 'Schultz, Simonis and Stokes', '1 Del Sol Terrace');
insert into KLUB (id,  Ime, Naslov) values (1562, 'Marquardt and Sons', '6 Vahlen Terrace');
insert into KLUB (id,  Ime, Naslov) values (1563, 'Gleason Inc', '51 Debra Parkway');
insert into KLUB (id,  Ime, Naslov) values (1564, 'Kessler-McDermott', '172 Petterle Lane');
insert into KLUB (id,  Ime, Naslov) values (1565, 'Larson, Cremin and Anderson', '0 Loftsgordon Alley');
insert into KLUB (id,  Ime, Naslov) values (1566, 'Dickens-Mraz', '68358 Granby Park');
insert into KLUB (id,  Ime, Naslov) values (1567, 'Satterfield-Lind', '4860 Nevada Point');
insert into KLUB (id,  Ime, Naslov) values (1568, 'Hintz-Vandervort', '66 Anhalt Point');
insert into KLUB (id,  Ime, Naslov) values (1569, 'Jacobs-Block', '3 Summit Lane');
insert into KLUB (id,  Ime, Naslov) values (1570, 'Romaguera-Doyle', '61043 Carey Road');
insert into KLUB (id,  Ime, Naslov) values (1571, 'Gislason Emmerich and Christiansen', '27444 Anderson Trail');
insert into KLUB (id,  Ime, Naslov) values (1572, 'Bernier Crona and Wisozk', '2 Sachtjen Park');
insert into KLUB (id,  Ime, Naslov) values (1573, 'Volkman Dooley and Prosacco', '146 Northfield Place');
insert into KLUB (id,  Ime, Naslov) values (1574, 'Grant-Stokes', '2928 Bunting Street');
insert into KLUB (id,  Ime, Naslov) values (1575, 'Nader Langosh and Hintz', '7 Schiller Place');
insert into KLUB (id,  Ime, Naslov) values (1576, 'Roob Block and Douglas', '310 Comanche Terrace');
insert into KLUB (id,  Ime, Naslov) values (1577, 'Kunze O''Hara and Miller', '1 Sunbrook Terrace');
insert into KLUB (id,  Ime, Naslov) values (1578, 'Hammes O''Conner and O''Conner', '15 Debs Point');
insert into KLUB (id,  Ime, Naslov) values (1579, 'Schneider and Sons', '61 6th Parkway');
insert into KLUB (id,  Ime, Naslov) values (1580, 'Braun LLC', '32098 Pierstorff Junction');
insert into KLUB (id,  Ime, Naslov) values (1581, 'Macejkovic Daugherty and Hodkiewicz', '803 Ruskin Hill');
insert into KLUB (id,  Ime, Naslov) values (1582, 'Rodriguez Group', '8002 Lien Way');
insert into KLUB (id,  Ime, Naslov) values (1583, 'O''Conner-O''Reilly', '3078 Prairie Rose Point');
insert into KLUB (id,  Ime, Naslov) values (1584, 'Klocko Inc', '9 Judy Drive');
insert into KLUB (id,  Ime, Naslov) values (1585, 'Sanford, Von and Towne', '38742 Mcguire Terrace');
insert into KLUB (id,  Ime, Naslov) values (1586, 'Roberts-Cummings', '070 Spohn Circle');
insert into KLUB (id,  Ime, Naslov) values (1587, 'Gleason-Harvey', '4 Service Crossing');
insert into KLUB (id,  Ime, Naslov) values (1588, 'Kozey-Cole', '051 Huxley Point');
insert into KLUB (id,  Ime, Naslov) values (1589, 'Rempel-Davis', '2205 Prairieview Court');
insert into KLUB (id,  Ime, Naslov) values (1590, 'West-Prosacco', '028 Kim Alley');
insert into KLUB (id,  Ime, Naslov) values (1591, 'McDermott-Kuvalis', '6 Schurz Terrace');
insert into KLUB (id,  Ime, Naslov) values (1592, 'Walker-Quitzon', '15274 Rieder Park');
insert into KLUB (id,  Ime, Naslov) values (1593, 'Nikolaus LLC', '3669 Northview Avenue');
insert into KLUB (id,  Ime, Naslov) values (1594, 'Stehr-Sipes', '22 Superior Junction');
insert into KLUB (id,  Ime, Naslov) values (1595, 'Weber-Harvey', '631 Arrowood Crossing');
insert into KLUB (id,  Ime, Naslov) values (1596, 'Schmitt LLC', '86017 Declaration Court');
insert into KLUB (id,  Ime, Naslov) values (1597, 'Kuhic-Franecki', '7 Carey Pass');
insert into KLUB (id,  Ime, Naslov) values (1598, 'Corwin-Altenwerth', '0137 Goodland Place');
insert into KLUB (id,  Ime, Naslov) values (1599, 'Tremblay and Sons', '8 Dapin Crossing');
insert into KLUB (id,  Ime, Naslov) values (1600, 'Hintz-Crooks', '2 Rieder Junction');
insert into KLUB (id,  Ime, Naslov) values (1601, 'Lesch-Nikolaus', '10842 Trailsway Road');
insert into KLUB (id,  Ime, Naslov) values (1602, 'Deckow Hamill and Walsh', '95 3rd Parkway');
insert into KLUB (id,  Ime, Naslov) values (1603, 'Davis Inc', '4093 Onsgard Court');
insert into KLUB (id,  Ime, Naslov) values (1604, 'Weber Abshire and Bosco', '7 Eastlawn Point');
insert into KLUB (id,  Ime, Naslov) values (1605, 'Turner and Sons', '2 Kings Hill');
insert into KLUB (id,  Ime, Naslov) values (1606, 'Kilback Inc', '60043 Prentice Lane');
insert into KLUB (id,  Ime, Naslov) values (1607, 'Ankunding, Rempel and Reinger', '8113 Steensland Lane');
insert into KLUB (id,  Ime, Naslov) values (1608, 'Weissnat-Boyer', '579 Atwood Alley');
insert into KLUB (id,  Ime, Naslov) values (1609, 'Wehner-Blick', '4653 Debs Park');
insert into KLUB (id,  Ime, Naslov) values (1610, 'Boyer-Homenick', '5 Hansons Junction');
insert into KLUB (id,  Ime, Naslov) values (1611, 'Herzog LLC', '1 Eliot Drive');
insert into KLUB (id,  Ime, Naslov) values (1612, 'Schneider-DuBuque', '065 Stone Corner Street');
insert into KLUB (id,  Ime, Naslov) values (1613, 'Bartell-Shanahan', '9398 Lukken Avenue');
insert into KLUB (id,  Ime, Naslov) values (1614, 'O Hara LLC', '5886 Lighthouse Bay Crossing');
insert into KLUB (id,  Ime, Naslov) values (1615, 'Smitham, Yundt and Rath', '7473 Cambridge Hill');
insert into KLUB (id,  Ime, Naslov) values (1616, 'Koch Sauer and Schinner', '85 Manley Court');
insert into KLUB (id,  Ime, Naslov) values (1617, 'Yundt-Cruickshank', '941 Muir Terrace');
insert into KLUB (id,  Ime, Naslov) values (1618, 'Muller Simonis and Stanton', '9156 Scott Terrace');
insert into KLUB (id,  Ime, Naslov) values (1619, 'Hane LLC', '8 Everett Pass');
insert into KLUB (id,  Ime, Naslov) values (1620, 'Roberts Wiegand and Schmitt', '8 Eastlawn Crossing');
insert into KLUB (id,  Ime, Naslov) values (1621, 'Osinski-Orn', '3969 Karstens Parkway');
insert into KLUB (id,  Ime, Naslov) values (1622, 'Barton Moen and Schiller', '6 Kensington Pass');
insert into KLUB (id,  Ime, Naslov) values (1623, 'Will Group', '00997 Welch Plaza');
insert into KLUB (id,  Ime, Naslov) values (1624, 'Barrows-Gutmann', '3255 Manitowish Hill');
insert into KLUB (id,  Ime, Naslov) values (1625, 'Lockman Schimmel and Cummings', '33 Springs Park');
insert into KLUB (id,  Ime, Naslov) values (1626, 'Sanford-Brown', '44663 Dawn Hill');
insert into KLUB (id,  Ime, Naslov) values (1627, 'Koss-Koelpin', '7 Erie Road');
insert into KLUB (id,  Ime, Naslov) values (1628, 'Bernier-Rutherford', '85 John Wall Point');
insert into KLUB (id,  Ime, Naslov) values (1629, 'Ryan LLC', '77335 Sycamore Trail');
insert into KLUB (id,  Ime, Naslov) values (1630, 'Huels, McCullough and Roob', '8762 Weeping Birch Street');
insert into KLUB (id,  Ime, Naslov) values (1631, 'Mueller-Corkery', '0999 Eliot Plaza');
insert into KLUB (id,  Ime, Naslov) values (1632, 'Padberg Rempel and DuBuque', '72509 Wayridge Street');
insert into KLUB (id,  Ime, Naslov) values (1633, 'Gerlach-Spencer', '23 Monument Circle');
insert into KLUB (id,  Ime, Naslov) values (1634, 'Runolfsdottir Towne and Hirthe', '3 Grim Center');
insert into KLUB (id,  Ime, Naslov) values (1635, 'Orn Group', '92 Annamark Lane');
insert into KLUB (id,  Ime, Naslov) values (1636, 'Hirthe Gusikowski and Heathcote', '68 3rd Junction');
insert into KLUB (id,  Ime, Naslov) values (1637, 'Maggio and Sons', '19278 Schiller Road');
insert into KLUB (id,  Ime, Naslov) values (1638, 'Schulist-Mertz', '14282 Northwestern Drive');
insert into KLUB (id,  Ime, Naslov) values (1639, 'Rohan Group', '28 Sugar Park');
insert into KLUB (id,  Ime, Naslov) values (1640, 'Spencer-O Connell', '955 Bultman Place');
insert into KLUB (id,  Ime, Naslov) values (1641, 'Ratke Paucek and Boehm', '154 Cardinal Terrace');
insert into KLUB (id,  Ime, Naslov) values (1642, 'Turner Group', '5 Hazelcrest Crossing');
insert into KLUB (id,  Ime, Naslov) values (1643, 'Schmidt Kilback and Wisoky', '84225 5th Avenue');
insert into KLUB (id,  Ime, Naslov) values (1644, 'Pagac Trantow and Heathcote', '6728 Eliot Place');
insert into KLUB (id,  Ime, Naslov) values (1645, 'Zemlak-Cartwright', '1349 Macpherson Crossing');
insert into KLUB (id,  Ime, Naslov) values (1646, 'Emmerich-Grimes', '009 Buena Vista Pass');
insert into KLUB (id,  Ime, Naslov) values (1647, 'Hegmann-Borer', '279 Cottonwood Trail');
insert into KLUB (id,  Ime, Naslov) values (1648, 'Boehm Borer and Parisian', '53 Jana Pass');
insert into KLUB (id,  Ime, Naslov) values (1649, 'Goodwin Nicolas and Considine', '56 Schurz Road');
insert into KLUB (id,  Ime, Naslov) values (1650, 'Runolfsdottir Group', '11 Dunning Place');
insert into KLUB (id,  Ime, Naslov) values (1651, 'West Inc', '0 Roxbury Terrace');
insert into KLUB (id,  Ime, Naslov) values (1652, 'Littel Cartwright and Bahringer', '3 Leroy Hill');
insert into KLUB (id,  Ime, Naslov) values (1653, 'Runolfsson-Grant', '14 Fordem Hill');
insert into KLUB (id,  Ime, Naslov) values (1654, 'Treutel Inc', '7652 Summerview Terrace');
insert into KLUB (id,  Ime, Naslov) values (1655, 'Pollich-Cartwright', '7025 Donald Way');
insert into KLUB (id,  Ime, Naslov) values (1656, 'Kunde and Sons', '5 Stang Alley');
insert into KLUB (id,  Ime, Naslov) values (1657, 'Wyman-Flatley', '7553 Gerald Point');
insert into KLUB (id,  Ime, Naslov) values (1658, 'Rosenbaum LLC', '49 Service Lane');
insert into KLUB (id,  Ime, Naslov) values (1659, 'Morissette-Conn', '6134 Oxford Way');
insert into KLUB (id,  Ime, Naslov) values (1660, 'Hartmann Hammes and Zieme', '4536 Almo Lane');
insert into KLUB (id,  Ime, Naslov) values (1661, 'Lubowitz Turner and Pouros', '19501 Starling Point');
insert into KLUB (id,  Ime, Naslov) values (1662, 'Fay Group', '8856 Parkside Point');
insert into KLUB (id,  Ime, Naslov) values (1663, 'Yost Rolfson and Ortiz', '43 Derek Park');
insert into KLUB (id,  Ime, Naslov) values (1664, 'Hirthe Inc', '5714 Chive Crossing');
insert into KLUB (id,  Ime, Naslov) values (1665, 'Moen-Schowalter', '1 Sachs Court');
insert into KLUB (id,  Ime, Naslov) values (1666, 'Ortiz-Moen', '54208 Amoth Drive');
insert into KLUB (id,  Ime, Naslov) values (1667, 'Dietrich-Cole', '5549 Moulton Road');
insert into KLUB (id,  Ime, Naslov) values (1668, 'Haley Padberg and Dietrich', '900 Gulseth Pass');
insert into KLUB (id,  Ime, Naslov) values (1669, 'Pouros Inc', '2525 Oneill Center');
insert into KLUB (id,  Ime, Naslov) values (1670, 'Weber-Buckridge', '73 Maple Center');
insert into KLUB (id,  Ime, Naslov) values (1671, 'Schowalter-Hammes', '88313 Linden Place');
insert into KLUB (id,  Ime, Naslov) values (1672, 'Skiles-Fadel', '60 Manufacturers Trail');
insert into KLUB (id,  Ime, Naslov) values (1673, 'Grant and Sons', '55589 Green Ridge Crossing');
insert into KLUB (id,  Ime, Naslov) values (1674, 'Kuhlman Group', '5324 Hauk Plaza');
insert into KLUB (id,  Ime, Naslov) values (1675, 'Conn Flatley and Schuster', '80881 Brentwood Alley');
insert into KLUB (id,  Ime, Naslov) values (1676, 'Vandervort, Stark and Stracke', '432 Reindahl Lane');
insert into KLUB (id,  Ime, Naslov) values (1677, 'Thiel Hilll and Waters', '65 Farragut Center');
insert into KLUB (id,  Ime, Naslov) values (1678, 'Keebler-Monahan', '04 Cody Crossing');
insert into KLUB (id,  Ime, Naslov) values (1679, 'Christiansen-Mann', '8071 Grasskamp Alley');
insert into KLUB (id,  Ime, Naslov) values (1680, 'Gutmann Oberbrunner and Moore', '1 Manitowish Lane');
insert into KLUB (id,  Ime, Naslov) values (1681, 'Romaguera-Abshire', '6 Declaration Trail');
insert into KLUB (id,  Ime, Naslov) values (1682, 'Metz-Kassulke', '28 Tomscot Hill');
insert into KLUB (id,  Ime, Naslov) values (1683, 'Rau Boehm and Durgan', '18 Eagle Crest Road');
insert into KLUB (id,  Ime, Naslov) values (1684, 'Buckridge-Olson', '25 Armistice Drive');
insert into KLUB (id,  Ime, Naslov) values (1685, 'Heaney Kozey and Blick', '3 Debs Place');
insert into KLUB (id,  Ime, Naslov) values (1686, 'Bednar Group', '7409 Messerschmidt Point');
insert into KLUB (id,  Ime, Naslov) values (1687, 'Pfeffer LLC', '29 Hazelcrest Hill');
insert into KLUB (id,  Ime, Naslov) values (1688, 'Littel-Lakin', '3964 Cottonwood Alley');
insert into KLUB (id,  Ime, Naslov) values (1689, 'Prohaska Larson and Krajcik', '4275 Springview Road');
insert into KLUB (id,  Ime, Naslov) values (1690, 'Gislason Inc', '70 Ridgeway Way');
insert into KLUB (id,  Ime, Naslov) values (1691, 'McKenzie-Wisoky', '3347 Judy Avenue');
insert into KLUB (id,  Ime, Naslov) values (1692, 'Deckow-Bins', '881 Melby Hill');
insert into KLUB (id,  Ime, Naslov) values (1693, 'Little Inc', '178 Reinke Alley');
insert into KLUB (id,  Ime, Naslov) values (1694, 'Stroman Inc', '94 Ruskin Pass');
insert into KLUB (id,  Ime, Naslov) values (1695, 'Herman LLC', '8455 Pierstorff Road');
insert into KLUB (id,  Ime, Naslov) values (1696, 'Zulauf Group', '89240 Schlimgen Avenue');
insert into KLUB (id,  Ime, Naslov) values (1697, 'Gerlach and Sons', '8008 Cardinal Avenue');
insert into KLUB (id,  Ime, Naslov) values (1698, 'Schoen LLC', '517 Fieldstone Avenue');
insert into KLUB (id,  Ime, Naslov) values (1699, 'Schimmel, Stiedemann and Bauch', '09 Corry Parkway');
insert into KLUB (id,  Ime, Naslov) values (1700, 'Durgan LLC', '3 Vidon Park');
insert into KLUB (id,  Ime, Naslov) values (1701, 'Fisher Moen and Hagenes', '27841 Larry Pass');
insert into KLUB (id,  Ime, Naslov) values (1702, 'Reichert, Barton and Corkery', '79392 Prentice Road');
insert into KLUB (id,  Ime, Naslov) values (1703, 'Weimann Group', '748 Merrick Circle');
insert into KLUB (id,  Ime, Naslov) values (1704, 'Cole-Kuhic', '391 David Court');
insert into KLUB (id,  Ime, Naslov) values (1705, 'Herzog Kuhlman and Cummerata', '65301 Northfield Way');
insert into KLUB (id,  Ime, Naslov) values (1706, 'Cummings Larson and Will', '352 Muir Parkway');
insert into KLUB (id,  Ime, Naslov) values (1707, 'Langosh-Bernier', '4 Homewood Point');
insert into KLUB (id,  Ime, Naslov) values (1708, 'Lockman Group', '772 Clove Park');
insert into KLUB (id,  Ime, Naslov) values (1709, 'Schultz-Boehm', '94359 Killdeer Drive');
insert into KLUB (id,  Ime, Naslov) values (1710, 'Paucek-Beahan', '7820 Spenser Drive');
insert into KLUB (id,  Ime, Naslov) values (1711, 'Hudson-Runolfsdottir', '55 Hayes Plaza');
insert into KLUB (id,  Ime, Naslov) values (1712, 'Funk-Carter', '0 Algoma Pass');
insert into KLUB (id,  Ime, Naslov) values (1713, 'Ullrich-Leffler', '79684 Ridgeview Road');
insert into KLUB (id,  Ime, Naslov) values (1714, 'Bahringer-O''Conner', '56027 Dorton Way');
insert into KLUB (id,  Ime, Naslov) values (1715, 'Bauch-Beier', '37 Wayridge Lane');
insert into KLUB (id,  Ime, Naslov) values (1716, 'Rogahn Keeling and Becker', '29229 Dennis Road');
insert into KLUB (id,  Ime, Naslov) values (1717, 'Hoeger Wyman and Mills', '45579 Bay Alley');
insert into KLUB (id,  Ime, Naslov) values (1718, 'Simonis Group', '8 Butternut Avenue');
insert into KLUB (id,  Ime, Naslov) values (1719, 'Senger LLC', '5 Cherokee Pass');
insert into KLUB (id,  Ime, Naslov) values (1720, 'Douglas LLC', '81032 Pearson Circle');
insert into KLUB (id,  Ime, Naslov) values (1721, 'Kuvalis-Hodkiewicz', '2 Bartillon Terrace');
insert into KLUB (id,  Ime, Naslov) values (1722, 'Fisher Kozey and Rogahn', '6157 Tennyson Point');
insert into KLUB (id,  Ime, Naslov) values (1723, 'Mitchell-Johnston', '2 Blackbird Drive');
insert into KLUB (id,  Ime, Naslov) values (1724, 'Abernathy Group', '6 Pine View Terrace');
insert into KLUB (id,  Ime, Naslov) values (1725, 'Gulgowski LLC', '4565 Cherokee Trail');
insert into KLUB (id,  Ime, Naslov) values (1726, 'Mayer LLC', '51 Mandrake Junction');
insert into KLUB (id,  Ime, Naslov) values (1727, 'Hagenes-Mosciski', '5603 Cordelia Parkway');
insert into KLUB (id,  Ime, Naslov) values (1728, 'Christiansen-Sanford', '1 Starling Lane');
insert into KLUB (id,  Ime, Naslov) values (1729, 'Bauch LLC', '258 Springs Parkway');
insert into KLUB (id,  Ime, Naslov) values (1730, 'Schmitt-Muller', '1 Paget Terrace');
insert into KLUB (id,  Ime, Naslov) values (1731, 'Smith Inc', '4276 American Court');
insert into KLUB (id,  Ime, Naslov) values (1732, 'Schneider Inc', '2096 Forest Run Hill');
insert into KLUB (id,  Ime, Naslov) values (1733, 'Schmitt Watsica and Davis', '9 Cambridge Center');
insert into KLUB (id,  Ime, Naslov) values (1734, 'Cassin and Sons', '5 Summerview Trail');
insert into KLUB (id,  Ime, Naslov) values (1735, 'Hauck Denesik and Vandervort', '5 Old Shore Hill');
insert into KLUB (id,  Ime, Naslov) values (1736, 'Wilderman LLC', '2 Clove Terrace');
insert into KLUB (id,  Ime, Naslov) values (1737, 'Kessler-Johnson', '7 Ohio Plaza');
insert into KLUB (id,  Ime, Naslov) values (1738, 'Weber Inc', '12938 Reinke Drive');
insert into KLUB (id,  Ime, Naslov) values (1739, 'Weimann and Sons', '6893 Melvin Plaza');
insert into KLUB (id,  Ime, Naslov) values (1740, 'Jast Inc', '435 Judy Junction');
insert into KLUB (id,  Ime, Naslov) values (1741, 'Parker-Johnston', '7844 Truax Pass');
insert into KLUB (id,  Ime, Naslov) values (1742, 'Schuster-Schmeler', '5953 Huxley Pass');
insert into KLUB (id,  Ime, Naslov) values (1743, 'Stoltenberg-Hirthe', '11974 Shelley Circle');
insert into KLUB (id,  Ime, Naslov) values (1744, 'Klein Group', '4 Eliot Court');
insert into KLUB (id,  Ime, Naslov) values (1745, 'Grant Cummerata and Veum', '41589 Daystar Lane');
insert into KLUB (id,  Ime, Naslov) values (1746, 'Vandervort LLC', '299 Hansons Drive');
insert into KLUB (id,  Ime, Naslov) values (1747, 'Walsh-Dooley', '9523 Sloan Place');
insert into KLUB (id,  Ime, Naslov) values (1748, 'Jacobson and Sons', '6284 Browning Drive');
insert into KLUB (id,  Ime, Naslov) values (1749, 'Considine Inc', '037 Golf Plaza');
insert into KLUB (id,  Ime, Naslov) values (1750, 'Hand and Sons', '33289 2nd Junction');
insert into KLUB (id,  Ime, Naslov) values (1751, 'Kovacek, Upton and Ferry', '40949 Northwestern Point');
insert into KLUB (id,  Ime, Naslov) values (1752, 'Cremin and Sons', '1 Petterle Place');
insert into KLUB (id,  Ime, Naslov) values (1753, 'Goldner LLC', '3 Mallory Pass');
insert into KLUB (id,  Ime, Naslov) values (1754, 'Lehner Inc', '9 Gerald Court');
insert into KLUB (id,  Ime, Naslov) values (1755, 'Hoeger LLC', '8716 Myrtle Parkway');
insert into KLUB (id,  Ime, Naslov) values (1756, 'Zulauf Zboncak and Wisozk', '2271 Anniversary Drive');
insert into KLUB (id,  Ime, Naslov) values (1757, 'Ryan Pfannerstill and Kerluke', '96277 Doe Crossing Avenue');
insert into KLUB (id,  Ime, Naslov) values (1758, 'Hodkiewicz-Rice', '860 Novick Point');
insert into KLUB (id,  Ime, Naslov) values (1759, 'Schaefer Inc', '02 Sachs Plaza');
insert into KLUB (id,  Ime, Naslov) values (1760, 'Blick-Harber', '9923 Dayton Alley');
insert into KLUB (id,  Ime, Naslov) values (1761, 'Lang Lebsack and Lowe', '1 Cordelia Pass');
insert into KLUB (id,  Ime, Naslov) values (1762, 'Walker LLC', '20905 Lunder Circle');
insert into KLUB (id,  Ime, Naslov) values (1763, 'Cronin Tremblay and Schmidt', '08 Gateway Center');
insert into KLUB (id,  Ime, Naslov) values (1764, 'Bogisich-Gibson', '52818 Almo Park');
insert into KLUB (id,  Ime, Naslov) values (1765, 'Barrows Lynch and Shields', '329 Springs Avenue');
insert into KLUB (id,  Ime, Naslov) values (1766, 'Emard Conn and Ratke', '24717 East Lane');
insert into KLUB (id,  Ime, Naslov) values (1767, 'Brakus-Goyette', '1157 Cardinal Drive');
insert into KLUB (id,  Ime, Naslov) values (1768, 'Boehm-Haag', '8 Nobel Point');
insert into KLUB (id,  Ime, Naslov) values (1769, 'Cremin-Fahey', '06358 Hollow Ridge Trail');
insert into KLUB (id,  Ime, Naslov) values (1770, 'Feil-Hills', '7 Esch Point');
insert into KLUB (id,  Ime, Naslov) values (1771, 'Stokes LLC', '358 Burning Wood Junction');
insert into KLUB (id,  Ime, Naslov) values (1772, 'Quitzon-Ruecker', '67 Cordelia Plaza');
insert into KLUB (id,  Ime, Naslov) values (1773, 'Champlin, Williamson and Hartmann', '2 Corscot Parkway');
insert into KLUB (id,  Ime, Naslov) values (1774, 'Gaylord-Schiller', '4 Lakeland Street');
insert into KLUB (id,  Ime, Naslov) values (1775, 'Effertz-Quitzon', '4874 Red Cloud Point');
insert into KLUB (id,  Ime, Naslov) values (1776, 'Grant-Harvey', '87 Anderson Pass');
insert into KLUB (id,  Ime, Naslov) values (1777, 'McCullough, Wunsch and Mitchell', '1757 North Crossing');
insert into KLUB (id,  Ime, Naslov) values (1778, 'Strosin LLC', '26737 Crownhardt Avenue');
insert into KLUB (id,  Ime, Naslov) values (1779, 'Weimann Fahey and Kerluke', '48 Canary Junction');
insert into KLUB (id,  Ime, Naslov) values (1780, 'Heller Fadel and Douglas', '8 Sutteridge Circle');
insert into KLUB (id,  Ime, Naslov) values (1781, 'Kuphal Bergnaum and Schneider', '96 Portage Terrace');
insert into KLUB (id,  Ime, Naslov) values (1782, 'O Conner Nienow and Hills', '823 Gateway Junction');
insert into KLUB (id,  Ime, Naslov) values (1783, 'Gutkowski Senger and Wolf', '06 Jay Pass');
insert into KLUB (id,  Ime, Naslov) values (1784, 'Legros-Walsh', '76771 Rowland Circle');
insert into KLUB (id,  Ime, Naslov) values (1785, 'Bernier LLC', '355 Buhler Hill');
insert into KLUB (id,  Ime, Naslov) values (1786, 'Schulist Boyer and Ankunding', '9 Lunder Way');
insert into KLUB (id,  Ime, Naslov) values (1787, 'Waelchi Conroy and Rath', '69135 8th Terrace');
insert into KLUB (id,  Ime, Naslov) values (1788, 'Feest Inc', '22201 Troy Point');
insert into KLUB (id,  Ime, Naslov) values (1789, 'Zemlak-Berge', '2 Quincy Way');
insert into KLUB (id,  Ime, Naslov) values (1790, 'Murazik-Mraz', '6 Eagan Alley');
insert into KLUB (id,  Ime, Naslov) values (1791, 'Langosh Johnson and Gutkowski', '57022 Coolidge Street');
insert into KLUB (id,  Ime, Naslov) values (1792, 'Pfeffer-Schumm', '65 Kinsman Court');
insert into KLUB (id,  Ime, Naslov) values (1793, 'Welch-Dickinson', '637 Lakewood Gardens Crossing');
insert into KLUB (id,  Ime, Naslov) values (1794, 'Reichel Blick and Aufderhar', '7666 Rowland Plaza');
insert into KLUB (id,  Ime, Naslov) values (1795, 'Vandervort Group', '2346 Di Loreto Drive');
insert into KLUB (id,  Ime, Naslov) values (1796, 'Botsford-Mohr', '98 Northport Place');
insert into KLUB (id,  Ime, Naslov) values (1797, 'Batz Lind and Leuschke', '9 Hoepker Way');
insert into KLUB (id,  Ime, Naslov) values (1798, 'Trantow O Conner and Bailey', '2 Dottie Lane');
insert into KLUB (id,  Ime, Naslov) values (1799, 'Runte Corkery and Spencer', '24 Karstens Point');
insert into KLUB (id,  Ime, Naslov) values (1800, 'Volkman Lebsack and Hamill', '1 Summit Road');
insert into KLUB (id,  Ime, Naslov) values (1801, 'Kirlin-Kub', '7 Badeau Road');
insert into KLUB (id,  Ime, Naslov) values (1802, 'O Connell-Greenfelder', '61462 Erie Terrace');
insert into KLUB (id,  Ime, Naslov) values (1803, 'Veum Herzog and Koch', '74 Ronald Regan Place');
insert into KLUB (id,  Ime, Naslov) values (1804, 'Terry-Ebert', '9198 Rowland Street');
insert into KLUB (id,  Ime, Naslov) values (1805, 'Huels Harris and Goldner', '214 Pine View Junction');
insert into KLUB (id,  Ime, Naslov) values (1806, 'Walter Weber and Rodriguez', '70 Summer Ridge Pass');
insert into KLUB (id,  Ime, Naslov) values (1807, 'McDermott Yundt and Hettinger', '61989 Petterle Drive');
insert into KLUB (id,  Ime, Naslov) values (1808, 'Weber-Pfeffer', '356 Becker Trail');
insert into KLUB (id,  Ime, Naslov) values (1809, 'Lind-Walker', '50 Little Fleur Junction');
insert into KLUB (id,  Ime, Naslov) values (1810, 'Gerlach-Lueilwitz', '793 Dorton Circle');
insert into KLUB (id,  Ime, Naslov) values (1811, 'Koss LLC', '84 Merrick Road');
insert into KLUB (id,  Ime, Naslov) values (1812, 'Cartwright Group', '7390 6th Way');
insert into KLUB (id,  Ime, Naslov) values (1813, 'Breitenberg Hickle and Schmeler', '66 Maywood Court');
insert into KLUB (id,  Ime, Naslov) values (1814, 'Purdy-Becker', '333 Kensington Road');
insert into KLUB (id,  Ime, Naslov) values (1815, 'Hettinger-Miller', '84 Evergreen Terrace');
insert into KLUB (id,  Ime, Naslov) values (1816, 'Schulist-Grimes', '91375 Towne Park');
insert into KLUB (id,  Ime, Naslov) values (1817, 'Gulgowski-Marquardt', '7035 Stang Plaza');
insert into KLUB (id,  Ime, Naslov) values (1818, 'Kunde Swaniawski and Klein', '023 Alpine Hill');
insert into KLUB (id,  Ime, Naslov) values (1819, 'Altenwerth Stoltenberg and VonRueden', '06 New Castle Junction');
insert into KLUB (id,  Ime, Naslov) values (1820, 'Heathcote and Sons', '91460 Fremont Parkway');
insert into KLUB (id,  Ime, Naslov) values (1821, 'Dickinson Toy and Stanton', '9 Grasskamp Road');
insert into KLUB (id,  Ime, Naslov) values (1822, 'Cummerata Inc', '433 Golden Leaf Drive');
insert into KLUB (id,  Ime, Naslov) values (1823, 'Mante and Sons', '465 Annamark Place');
insert into KLUB (id,  Ime, Naslov) values (1824, 'McClure Cassin and Larson', '06579 Forster Point');
insert into KLUB (id,  Ime, Naslov) values (1825, 'Ledner Bailey and D''Amore', '51 Ronald Regan Road');
insert into KLUB (id,  Ime, Naslov) values (1826, 'Baumbach Dooley and Pollich', '876 Declaration Drive');
insert into KLUB (id,  Ime, Naslov) values (1827, 'Spencer Blick and Funk', '45 Starling Center');
insert into KLUB (id,  Ime, Naslov) values (1828, 'Hegmann Heathcote and Skiles', '747 Village Hill');
insert into KLUB (id,  Ime, Naslov) values (1829, 'Metz-Reilly', '33 Mariners Cove Lane');
insert into KLUB (id,  Ime, Naslov) values (1830, 'Rogahn-Crooks', '626 Acker Junction');
insert into KLUB (id,  Ime, Naslov) values (1831, 'Hayes Inc', '08 Menomonie Center');
insert into KLUB (id,  Ime, Naslov) values (1832, 'Runolfsdottir-Beier', '69 West Lane');
insert into KLUB (id,  Ime, Naslov) values (1833, 'Pagac-Gaylord', '0373 Iowa Park');
insert into KLUB (id,  Ime, Naslov) values (1834, 'Legros and Sons', '74101 Jackson Plaza');
insert into KLUB (id,  Ime, Naslov) values (1835, 'Lehner Klocko and Goodwin', '25 Hanson Center');
insert into KLUB (id,  Ime, Naslov) values (1836, 'Rodriguez Ratke and Thompson', '3976 Center Terrace');
insert into KLUB (id,  Ime, Naslov) values (1837, 'McGlynn Inc', '14159 Meadow Vale Way');
insert into KLUB (id,  Ime, Naslov) values (1838, 'Gleichner Metz and Zieme', '452 Brown Crossing');
insert into KLUB (id,  Ime, Naslov) values (1839, 'Bartell-Windler', '36604 Porter Road');
insert into KLUB (id,  Ime, Naslov) values (1840, 'Becker Group', '9 Muir Circle');
insert into KLUB (id,  Ime, Naslov) values (1841, 'Welch and Sons', '6 Sunfield Pass');
insert into KLUB (id,  Ime, Naslov) values (1842, 'Tillman Will and Hegmann', '3 Tennessee Parkway');
insert into KLUB (id,  Ime, Naslov) values (1843, 'Bernhard LLC', '85375 Memorial Trail');
insert into KLUB (id,  Ime, Naslov) values (1844, 'Labadie-Blanda', '0 Surrey Avenue');
insert into KLUB (id,  Ime, Naslov) values (1845, 'Schowalter-Bradtke', '124 Helena Drive');
insert into KLUB (id,  Ime, Naslov) values (1846, 'Schmidt-Wolf', '453 Dovetail Road');
insert into KLUB (id,  Ime, Naslov) values (1847, 'Fadel-Nienow', '76209 Summer Ridge Place');
insert into KLUB (id,  Ime, Naslov) values (1848, 'Runte Inc', '4026 Bunting Place');
insert into KLUB (id,  Ime, Naslov) values (1849, 'Haley LLC', '61 Service Alley');
insert into KLUB (id,  Ime, Naslov) values (1850, 'Harvey-Kerluke', '24 Tony Circle');
insert into KLUB (id,  Ime, Naslov) values (1851, 'Dicki-Rempel', '5 Novick Circle');
insert into KLUB (id,  Ime, Naslov) values (1852, 'Maggio and Sons', '67525 Graedel Trail');
insert into KLUB (id,  Ime, Naslov) values (1853, 'Russel Kovacek and Oberbrunner', '58 Artisan Parkway');
insert into KLUB (id,  Ime, Naslov) values (1854, 'Effertz-Renner', '0656 Old Gate Avenue');
insert into KLUB (id,  Ime, Naslov) values (1855, 'Muller Larkin and Marks', '50 Meadow Vale Avenue');
insert into KLUB (id,  Ime, Naslov) values (1856, 'Graham LLC', '8834 Stone Corner Pass');
insert into KLUB (id,  Ime, Naslov) values (1857, 'Rosenbaum-Lowe', '60812 Towne Junction');
insert into KLUB (id,  Ime, Naslov) values (1858, 'Runolfsdottir and Sons', '85 Karstens Avenue');
insert into KLUB (id,  Ime, Naslov) values (1859, 'Sporer Hayes and Durgan', '169 Oak Valley Road');
insert into KLUB (id,  Ime, Naslov) values (1860, 'Goldner Balistreri and Volkman', '1809 Independence Plaza');
insert into KLUB (id,  Ime, Naslov) values (1861, 'Orn Runolfsdottir and Hirthe', '1 Sunfield Hill');
insert into KLUB (id,  Ime, Naslov) values (1862, 'Hauck Inc', '2880 Raven Place');
insert into KLUB (id,  Ime, Naslov) values (1863, 'Quigley-Turcotte', '34169 Gale Hill');
insert into KLUB (id,  Ime, Naslov) values (1864, 'Bauch-Wiza', '9720 Cascade Plaza');
insert into KLUB (id,  Ime, Naslov) values (1865, 'Watsica Walsh and Bechtelar', '7 Amoth Street');
insert into KLUB (id,  Ime, Naslov) values (1866, 'Bayer Maggio and Feest', '23491 Crest Line Trail');
insert into KLUB (id,  Ime, Naslov) values (1867, 'McCullough Gusikowski and Waelchi', '0636 Sommers Place');
insert into KLUB (id,  Ime, Naslov) values (1868, 'Koepp and Sons', '68456 Kropf Avenue');
insert into KLUB (id,  Ime, Naslov) values (1869, 'Botsford Greenholt and Dickinson', '3 Lawn Park');
insert into KLUB (id,  Ime, Naslov) values (1870, 'Marquardt Green and Reilly', '010 Sloan Point');
insert into KLUB (id,  Ime, Naslov) values (1871, 'Heller-Adams', '64561 Waubesa Terrace');
insert into KLUB (id,  Ime, Naslov) values (1872, 'Baumbach Group', '979 Vahlen Alley');
insert into KLUB (id,  Ime, Naslov) values (1873, 'Streich Nikolaus and Bradtke', '0867 Stephen Road');
insert into KLUB (id,  Ime, Naslov) values (1874, 'Fay Hackett and Auer', '82 Delaware Lane');
insert into KLUB (id,  Ime, Naslov) values (1875, 'Heller-Jacobson', '85356 Mitchell Way');
insert into KLUB (id,  Ime, Naslov) values (1876, 'Murazik Group', '395 Bay Alley');
insert into KLUB (id,  Ime, Naslov) values (1877, 'Nienow LLC', '98857 Linden Court');
insert into KLUB (id,  Ime, Naslov) values (1878, 'Schultz-MacGyver', '69529 Vidon Plaza');
insert into KLUB (id,  Ime, Naslov) values (1879, 'Waelchi Hegmann and Langworth', '52883 Dapin Point');
insert into KLUB (id,  Ime, Naslov) values (1880, 'MacGyver Becker and Barrows', '96731 Bartelt Hill');
insert into KLUB (id,  Ime, Naslov) values (1881, 'Greenfelder-Robel', '2 7th Junction');
insert into KLUB (id,  Ime, Naslov) values (1882, 'Lemke Russel and Leuschke', '6 Evergreen Trail');
insert into KLUB (id,  Ime, Naslov) values (1883, 'Reinger-Quitzon', '8 Hanover Terrace');
insert into KLUB (id,  Ime, Naslov) values (1884, 'Crist-Will', '162 Vahlen Terrace');
insert into KLUB (id,  Ime, Naslov) values (1885, 'Krajcik Littel and Watsica', '9786 Continental Circle');
insert into KLUB (id,  Ime, Naslov) values (1886, 'Runte Inc', '4 Sunnyside Trail');
insert into KLUB (id,  Ime, Naslov) values (1887, 'McCullough Metz and Wintheiser', '61 Tony Trail');
insert into KLUB (id,  Ime, Naslov) values (1888, 'Wilkinson-Borer', '8 Clemons Junction');
insert into KLUB (id,  Ime, Naslov) values (1889, 'Keeling Bailey and Grimes', '18615 Waubesa Place');
insert into KLUB (id,  Ime, Naslov) values (1890, 'Ernser Kuphal and Hoppe', '27271 Eastlawn Crossing');
insert into KLUB (id,  Ime, Naslov) values (1891, 'Torphy-Ritchie', '85318 Morning Lane');
insert into KLUB (id,  Ime, Naslov) values (1892, 'Jaskolski Inc', '1 Claremont Parkway');
insert into KLUB (id,  Ime, Naslov) values (1893, 'Boehm-Nitzsche', '4 Express Park');
insert into KLUB (id,  Ime, Naslov) values (1894, 'Glover-Harvey', '55 Independence Point');
insert into KLUB (id,  Ime, Naslov) values (1895, 'Kirlin LLC', '7 Petterle Place');
insert into KLUB (id,  Ime, Naslov) values (1896, 'Dickinson-Klein', '15083 Weeping Birch Park');
insert into KLUB (id,  Ime, Naslov) values (1897, 'Borer Gorczany and Shanahan', '90 Boyd Avenue');
insert into KLUB (id,  Ime, Naslov) values (1898, 'Dooley-Olson', '4561 Arizona Junction');
insert into KLUB (id,  Ime, Naslov) values (1899, 'Jenkins Pagac and Fadel', '745 Magdeline Lane');
insert into KLUB (id,  Ime, Naslov) values (1900, 'Gottlieb Gulgowski and Padberg', '614 Derek Drive');
insert into KLUB (id,  Ime, Naslov) values (1901, 'Anderson Inc', '6728 Bay Center');
insert into KLUB (id,  Ime, Naslov) values (1902, 'Shields-Casper', '24813 Bashford Plaza');
insert into KLUB (id,  Ime, Naslov) values (1903, 'O Hara Shanahan and Tremblay', '35927 Hudson Pass');
insert into KLUB (id,  Ime, Naslov) values (1904, 'Gerlach Inc', '39426 Lerdahl Place');
insert into KLUB (id,  Ime, Naslov) values (1905, 'Gleason Becker and Mosciski', '72531 Dawn Street');
insert into KLUB (id,  Ime, Naslov) values (1906, 'Langworth Group', '5 Grover Pass');
insert into KLUB (id,  Ime, Naslov) values (1907, 'Jaskolski-Barton', '2842 Beilfuss Drive');
insert into KLUB (id,  Ime, Naslov) values (1908, 'Mante-Jacobs', '4 Prentice Alley');
insert into KLUB (id,  Ime, Naslov) values (1909, 'McCullough Group', '15 Forest Dale Drive');
insert into KLUB (id,  Ime, Naslov) values (1910, 'Kunze Volkman and Crooks', '25513 Grover Circle');
insert into KLUB (id,  Ime, Naslov) values (1911, 'Pouros-D Amore', '811 Magdeline Terrace');
insert into KLUB (id,  Ime, Naslov) values (1912, 'Beatty Inc', '13251 Brentwood Drive');
insert into KLUB (id,  Ime, Naslov) values (1913, 'Bosco D Amore and Kemmer', '4 Colorado Crossing');
insert into KLUB (id,  Ime, Naslov) values (1914, 'Johnston Group', '692 Sage Terrace');
insert into KLUB (id,  Ime, Naslov) values (1915, 'Schmidt Mitchell and Metz', '6713 Pawling Road');
insert into KLUB (id,  Ime, Naslov) values (1916, 'Ritchie-King', '48411 Artisan Avenue');
insert into KLUB (id,  Ime, Naslov) values (1917, 'Shields-Schneider', '967 Saint Paul Plaza');
insert into KLUB (id,  Ime, Naslov) values (1918, 'Schimmel-Kreiger', '641 Fremont Point');
insert into KLUB (id,  Ime, Naslov) values (1919, 'Wintheiser-Conn', '14439 Armistice Road');
insert into KLUB (id,  Ime, Naslov) values (1920, 'Halvorson-Hills', '0760 Arizona Plaza');
insert into KLUB (id,  Ime, Naslov) values (1921, 'Runolfsdottir-Collins', '2 Jay Junction');
insert into KLUB (id,  Ime, Naslov) values (1922, 'Waelchi and Sons', '0047 Sugar Court');
insert into KLUB (id,  Ime, Naslov) values (1923, 'Pfannerstill-Cronin', '9 Mayfield Point');
insert into KLUB (id,  Ime, Naslov) values (1924, 'Shields Klocko and Casper', '586 Eliot Hill');
insert into KLUB (id,  Ime, Naslov) values (1925, 'Aufderhar Mann and Bednar', '41 Bonner Alley');
insert into KLUB (id,  Ime, Naslov) values (1926, 'Macejkovic-Lynch', '72600 Southridge Parkway');
insert into KLUB (id,  Ime, Naslov) values (1927, 'Nolan and Sons', '3273 Cordelia Alley');
insert into KLUB (id,  Ime, Naslov) values (1928, 'Romaguera and Sons', '2 Grasskamp Trail');
insert into KLUB (id,  Ime, Naslov) values (1929, 'Stokes Group', '736 Scott Drive');
insert into KLUB (id,  Ime, Naslov) values (1930, 'Batz and Sons', '47 Spenser Court');
insert into KLUB (id,  Ime, Naslov) values (1931, 'Gleichner-Rodriguez', '5 Aberg Circle');
insert into KLUB (id,  Ime, Naslov) values (1932, 'VonRueden Ruecker and Sauer', '700 Clemons Plaza');
insert into KLUB (id,  Ime, Naslov) values (1933, 'Hand Predovic and Kreiger', '2547 Eastlawn Junction');
insert into KLUB (id,  Ime, Naslov) values (1934, 'Trantow-Lindgren', '3 Old Shore Place');
insert into KLUB (id,  Ime, Naslov) values (1935, 'Satterfield LLC', '3 Westridge Junction');
insert into KLUB (id,  Ime, Naslov) values (1936, 'McKenzie-Thiel', '44406 Red Cloud Trail');
insert into KLUB (id,  Ime, Naslov) values (1937, 'Leannon Klein and Schinner', '9 Scott Hill');
insert into KLUB (id,  Ime, Naslov) values (1938, 'Hermiston Jakubowski and Keebler', '79 Monument Alley');
insert into KLUB (id,  Ime, Naslov) values (1939, 'Schiller-Hudson', '3 Lerdahl Park');
insert into KLUB (id,  Ime, Naslov) values (1940, 'Schoen Hackett and Sipes', '54977 Northport Point');
insert into KLUB (id,  Ime, Naslov) values (1941, 'Kuphal and Sons', '93 4th Pass');
insert into KLUB (id,  Ime, Naslov) values (1942, 'MacGyver McDermott and Dickinson', '63 Carberry Center');
insert into KLUB (id,  Ime, Naslov) values (1943, 'Borer Pfannerstill and Hudson', '43 Riverside Circle');
insert into KLUB (id,  Ime, Naslov) values (1944, 'Rippin-Miller', '04 Glendale Center');
insert into KLUB (id,  Ime, Naslov) values (1945, 'Hettinger Waters and Gleason', '547 Northwestern Drive');
insert into KLUB (id,  Ime, Naslov) values (1946, 'Ferry and Sons', '84198 Memorial Avenue');
insert into KLUB (id,  Ime, Naslov) values (1947, 'McCullough Ferry and Lynch', '6459 Hooker Terrace');
insert into KLUB (id,  Ime, Naslov) values (1948, 'Kub-Parker', '30753 Kenwood Alley');
insert into KLUB (id,  Ime, Naslov) values (1949, 'Feeney-Pollich', '452 Dunning Avenue');
insert into KLUB (id,  Ime, Naslov) values (1950, 'Batz Inc', '76130 Monterey Avenue');
insert into KLUB (id,  Ime, Naslov) values (1951, 'Towne-Green', '82 Milwaukee Trail');
insert into KLUB (id,  Ime, Naslov) values (1952, 'Russel-Pacocha', '83176 Derek Parkway');
insert into KLUB (id,  Ime, Naslov) values (1953, 'Heaney and Sons', '72 Independence Road');
insert into KLUB (id,  Ime, Naslov) values (1954, 'Quitzon and Sons', '16948 Burrows Trail');
insert into KLUB (id,  Ime, Naslov) values (1955, 'Padberg-Kub', '3 Thierer Crossing');
insert into KLUB (id,  Ime, Naslov) values (1956, 'Sanford Bednar and Runolfsson', '0 Stoughton Hill');
insert into KLUB (id,  Ime, Naslov) values (1957, 'Wiegand Group', '8841 Towne Lane');
insert into KLUB (id,  Ime, Naslov) values (1958, 'Schowalter-Kling', '323 Hoard Center');
insert into KLUB (id,  Ime, Naslov) values (1959, 'Beier Inc', '5 Lawn Lane');
insert into KLUB (id,  Ime, Naslov) values (1960, 'Cummerata-Leffler', '249 Dakota Street');
insert into KLUB (id,  Ime, Naslov) values (1961, 'McKenzie Group', '46780 Gerald Pass');
insert into KLUB (id,  Ime, Naslov) values (1962, 'Schmeler LLC', '629 Luster Court');
insert into KLUB (id,  Ime, Naslov) values (1963, 'Effertz-Sipes', '625 Eagle Crest Circle');
insert into KLUB (id,  Ime, Naslov) values (1964, 'Funk-Schmidt', '60635 Schiller Hill');
insert into KLUB (id,  Ime, Naslov) values (1965, 'DuBuque-O Connell', '3 Dunning Point');
insert into KLUB (id,  Ime, Naslov) values (1966, 'Kemmer-Bechtelar', '708 Scott Parkway');
insert into KLUB (id,  Ime, Naslov) values (1967, 'Welch-Bayer', '84754 Carey Way');
insert into KLUB (id,  Ime, Naslov) values (1968, 'Fadel LLC', '47549 Sunnyside Plaza');
insert into KLUB (id,  Ime, Naslov) values (1969, 'Lubowitz-Farrell', '30 Holy Cross Trail');
insert into KLUB (id,  Ime, Naslov) values (1970, 'Bradtke Rempel and Vandervort', '4084 Dunning Avenue');
insert into KLUB (id,  Ime, Naslov) values (1971, 'Botsford LLC', '77849 Jay Crossing');
insert into KLUB (id,  Ime, Naslov) values (1972, 'Pfeffer-Dickinson', '07 Fairview Junction');
insert into KLUB (id,  Ime, Naslov) values (1973, 'Langworth-Osinski', '309 Graceland Terrace');
insert into KLUB (id,  Ime, Naslov) values (1974, 'Heaney and Sons', '21589 Lakeland Trail');
insert into KLUB (id,  Ime, Naslov) values (1975, 'Homenick-Schinner', '0221 Springview Crossing');
insert into KLUB (id,  Ime, Naslov) values (1976, 'Ondricka Weissnat and Bogan', '24779 Mosinee Alley');
insert into KLUB (id,  Ime, Naslov) values (1977, 'Murray Inc', '15 Meadow Vale Place');
insert into KLUB (id,  Ime, Naslov) values (1978, 'Wiegand and Sons', '246 8th Pass');
insert into KLUB (id,  Ime, Naslov) values (1979, 'Schmeler Ortiz and Borer', '48 Crowley Drive');
insert into KLUB (id,  Ime, Naslov) values (1980, 'Donnelly Inc', '53378 Dexter Drive');
insert into KLUB (id,  Ime, Naslov) values (1981, 'Jast-Johns', '4220 Di Loreto Point');
insert into KLUB (id,  Ime, Naslov) values (1982, 'Hahn-Collins', '5919 Little Fleur Pass');
insert into KLUB (id,  Ime, Naslov) values (1983, 'Stroman-Feeney', '8082 Maryland Place');
insert into KLUB (id,  Ime, Naslov) values (1984, 'Stanton Haley and Koelpin', '577 Sugar Alley');
insert into KLUB (id,  Ime, Naslov) values (1985, 'Rice and Sons', '13 Mariners Cove Point');
insert into KLUB (id,  Ime, Naslov) values (1986, 'Hyatt Erdman and Hauck', '46 Kings Lane');
insert into KLUB (id,  Ime, Naslov) values (1987, 'O Conner Hartmann and Kiehn', '908 Barby Hill');
insert into KLUB (id,  Ime, Naslov) values (1988, 'Mann Inc', '37651 Riverside Hill');
insert into KLUB (id,  Ime, Naslov) values (1989, 'Quigley and Sons', '806 Starling Street');
insert into KLUB (id,  Ime, Naslov) values (1990, 'Swift Inc', '70 Caliangt Crossing');
insert into KLUB (id,  Ime, Naslov) values (1991, 'Fadel Beier and Cronin', '4959 Brickson Park Lane');
insert into KLUB (id,  Ime, Naslov) values (1992, 'Zulauf LLC', '7 Ryan Point');
insert into KLUB (id,  Ime, Naslov) values (1993, 'Zemlak Inc', '7 Nancy Trail');
insert into KLUB (id,  Ime, Naslov) values (1994, 'West LLC', '58088 Sauthoff Parkway');
insert into KLUB (id,  Ime, Naslov) values (1995, 'Stracke-Dooley', '47467 Eagan Point');
insert into KLUB (id,  Ime, Naslov) values (1996, 'Boyle Inc', '43085 Parkside Trail');
insert into KLUB (id,  Ime, Naslov) values (1997, 'Kuvalis LLC', '403 Westridge Park');
insert into KLUB (id,  Ime, Naslov) values (1998, 'Lueilwitz Inc', '47032 Mayer Point');
insert into KLUB (id,  Ime, Naslov) values (1999, 'Christiansen-Little', '78646 Bashford Terrace');
insert into KLUB (id,  Ime, Naslov) values (2000, 'Block Powlowski and Weimann', '3 Hintze Pass');
