create table klub (
	id INT,
	Ime VARCHAR(50),
	Naslov VARCHAR(50)
);
insert into klub (id, Ime, Naslov) values (2001, 'Wikivu', '3375 Dawn Trail');
insert into klub (id, Ime, Naslov) values (2002, 'Centimia', '628 Blue Bill Park Crossing');
insert into klub (id, Ime, Naslov) values (2003, 'Riffpedia', '0031 Coleman Alley');
insert into klub (id, Ime, Naslov) values (2004, 'Vidoo', '4206 Carioca Avenue');
insert into klub (id, Ime, Naslov) values (2005, 'Gabtune', '9 Pine View Park');
insert into klub (id, Ime, Naslov) values (2006, 'Jaxnation', '5168 Drewry Pass');
insert into klub (id, Ime, Naslov) values (2007, 'Jabberstorm', '2 John Wall Court');
insert into klub (id, Ime, Naslov) values (2008, 'Thoughtstorm', '95404 Thompson Plaza');
insert into klub (id, Ime, Naslov) values (2009, 'Bluezoom', '939 Artisan Parkway');
insert into klub (id, Ime, Naslov) values (2010, 'Skilith', '6 Mayer Drive');
insert into klub (id, Ime, Naslov) values (2011, 'Jabberstorm', '73 Darwin Hill');
insert into klub (id, Ime, Naslov) values (2012, 'Wikizz', '5 Maple Avenue');
insert into klub (id, Ime, Naslov) values (2013, 'Quinu', '3676 Golf View Crossing');
insert into klub (id, Ime, Naslov) values (2014, 'Eare', '74 Di Loreto Drive');
insert into klub (id, Ime, Naslov) values (2015, 'Blogtag', '558 Thackeray Crossing');
insert into klub (id, Ime, Naslov) values (2016, 'Feedmix', '2 Little Fleur Place');
insert into klub (id, Ime, Naslov) values (2017, 'Ntag', '76 Clyde Gallagher Road');
insert into klub (id, Ime, Naslov) values (2018, 'Realbuzz', '13 Derek Avenue');
insert into klub (id, Ime, Naslov) values (2019, 'Riffpedia', '9 Transport Street');
insert into klub (id, Ime, Naslov) values (2020, 'Browsezoom', '2103 Dwight Place');
insert into klub (id, Ime, Naslov) values (2021, 'Thoughtbridge', '13 Bunting Way');
insert into klub (id, Ime, Naslov) values (2022, 'Ozu', '57556 Rusk Center');
insert into klub (id, Ime, Naslov) values (2023, 'Browsecat', '69 Granby Way');
insert into klub (id, Ime, Naslov) values (2024, 'Babbleset', '004 Cherokee Drive');
insert into klub (id, Ime, Naslov) values (2025, 'Riffpath', '88 Helena Parkway');
insert into klub (id, Ime, Naslov) values (2026, 'Trilith', '3 Buell Circle');
insert into klub (id, Ime, Naslov) values (2027, 'Edgeblab', '9 Fulton Circle');
insert into klub (id, Ime, Naslov) values (2028, 'Skippad', '235 Maywood Junction');
insert into klub (id, Ime, Naslov) values (2029, 'Reallinks', '768 Charing Cross Road');
insert into klub (id, Ime, Naslov) values (2030, 'Demimbu', '3 West Alley');
insert into klub (id, Ime, Naslov) values (2031, 'Trunyx', '49839 Riverside Drive');
insert into klub (id, Ime, Naslov) values (2032, 'Zoomlounge', '6 Karstens Drive');
insert into klub (id, Ime, Naslov) values (2033, 'Ainyx', '425 Loomis Avenue');
insert into klub (id, Ime, Naslov) values (2034, 'Demimbu', '6 Lien Court');
insert into klub (id, Ime, Naslov) values (2035, 'Oyoba', '6 Upham Point');
insert into klub (id, Ime, Naslov) values (2036, 'Wordware', '51071 Tony Drive');
insert into klub (id, Ime, Naslov) values (2037, 'Skibox', '138 Hermina Place');
insert into klub (id, Ime, Naslov) values (2038, 'Vipe', '99 Melody Road');
insert into klub (id, Ime, Naslov) values (2039, 'Ooba', '652 Oriole Junction');
insert into klub (id, Ime, Naslov) values (2040, 'Pixope', '33199 Maryland Lane');
insert into klub (id, Ime, Naslov) values (2041, 'Jaxworks', '349 Columbus Drive');
insert into klub (id, Ime, Naslov) values (2042, 'Skiba', '03915 Maple Wood Avenue');
insert into klub (id, Ime, Naslov) values (2043, 'Skalith', '5 Blackbird Parkway');
insert into klub (id, Ime, Naslov) values (2044, 'Izio', '5515 Northfield Drive');
insert into klub (id, Ime, Naslov) values (2045, 'Browsetype', '32006 Hazelcrest Avenue');
insert into klub (id, Ime, Naslov) values (2046, 'Shufflester', '9257 Novick Pass');
insert into klub (id, Ime, Naslov) values (2047, 'Wordify', '64 Milwaukee Point');
insert into klub (id, Ime, Naslov) values (2048, 'Demivee', '02 Jenifer Alley');
insert into klub (id, Ime, Naslov) values (2049, 'Brightbean', '794 Granby Center');
insert into klub (id, Ime, Naslov) values (2050, 'Skinix', '032 Ohio Court');
insert into klub (id, Ime, Naslov) values (2051, 'Livefish', '0836 Nobel Hill');
insert into klub (id, Ime, Naslov) values (2052, 'Shuffledrive', '1346 Saint Paul Drive');
insert into klub (id, Ime, Naslov) values (2053, 'Zooxo', '0485 Burrows Drive');
insert into klub (id, Ime, Naslov) values (2054, 'Kimia', '40 Hovde Terrace');
insert into klub (id, Ime, Naslov) values (2055, 'Kayveo', '05637 Marcy Plaza');
insert into klub (id, Ime, Naslov) values (2056, 'Skipfire', '33579 Ryan Center');
insert into klub (id, Ime, Naslov) values (2057, 'JumpXS', '1 Bluestem Circle');
insert into klub (id, Ime, Naslov) values (2058, 'Oyoloo', '86173 Fair Oaks Way');
insert into klub (id, Ime, Naslov) values (2059, 'Omba', '41 Mandrake Alley');
insert into klub (id, Ime, Naslov) values (2060, 'Thoughtsphere', '932 Manley Alley');
insert into klub (id, Ime, Naslov) values (2061, 'Edgeify', '0285 Warbler Street');
insert into klub (id, Ime, Naslov) values (2062, 'Myworks', '58 Old Gate Avenue');
insert into klub (id, Ime, Naslov) values (2063, 'Fiveclub', '232 Ridgeway Junction');
insert into klub (id, Ime, Naslov) values (2064, 'Npath', '6437 Schurz Street');
insert into klub (id, Ime, Naslov) values (2065, 'Fivebridge', '50 Tennessee Circle');
insert into klub (id, Ime, Naslov) values (2066, 'Photospace', '26 Graedel Parkway');
insert into klub (id, Ime, Naslov) values (2067, 'Twinte', '2 Cordelia Drive');
insert into klub (id, Ime, Naslov) values (2068, 'Voonyx', '75905 Hollow Ridge Center');
insert into klub (id, Ime, Naslov) values (2069, 'Oozz', '36656 Ridge Oak Circle');
insert into klub (id, Ime, Naslov) values (2070, 'Reallinks', '4 Hollow Ridge Street');
insert into klub (id, Ime, Naslov) values (2071, 'JumpXS', '933 Bellgrove Court');
insert into klub (id, Ime, Naslov) values (2072, 'Photojam', '2206 Duke Plaza');
insert into klub (id, Ime, Naslov) values (2073, 'Meetz', '27120 Golf View Parkway');
insert into klub (id, Ime, Naslov) values (2074, 'Mita', '133 Pond Pass');
insert into klub (id, Ime, Naslov) values (2075, 'Rhyloo', '9707 Lukken Plaza');
insert into klub (id, Ime, Naslov) values (2076, 'Oba', '27046 Spohn Park');
insert into klub (id, Ime, Naslov) values (2077, 'Kwilith', '60901 Brown Road');
insert into klub (id, Ime, Naslov) values (2078, 'Buzzshare', '99556 Dawn Center');
insert into klub (id, Ime, Naslov) values (2079, 'Twitterbridge', '807 Spohn Park');
insert into klub (id, Ime, Naslov) values (2080, 'Kazu', '6 Hoard Parkway');
insert into klub (id, Ime, Naslov) values (2081, 'Flashset', '3 Orin Center');
insert into klub (id, Ime, Naslov) values (2082, 'Blogtag', '4 Columbus Hill');
insert into klub (id, Ime, Naslov) values (2083, 'Thoughtstorm', '674 American Drive');
insert into klub (id, Ime, Naslov) values (2084, 'Brainlounge', '0 Shoshone Circle');
insert into klub (id, Ime, Naslov) values (2085, 'Linklinks', '40 Ronald Regan Avenue');
insert into klub (id, Ime, Naslov) values (2086, 'Zoovu', '6 Cottonwood Lane');
insert into klub (id, Ime, Naslov) values (2087, 'Skipstorm', '397 Mitchell Circle');
insert into klub (id, Ime, Naslov) values (2088, 'Photobug', '3 Anniversary Place');
insert into klub (id, Ime, Naslov) values (2089, 'Oyoba', '90 Moland Parkway');
insert into klub (id, Ime, Naslov) values (2090, 'Linklinks', '53 Hoepker Hill');
insert into klub (id, Ime, Naslov) values (2091, 'Dynazzy', '84144 Sherman Road');
insert into klub (id, Ime, Naslov) values (2092, 'Pixonyx', '5 Welch Hill');
insert into klub (id, Ime, Naslov) values (2093, 'Topicshots', '62 La Follette Court');
insert into klub (id, Ime, Naslov) values (2094, 'Camido', '3 1st Lane');
insert into klub (id, Ime, Naslov) values (2095, 'Shuffletag', '6 Morningstar Place');
insert into klub (id, Ime, Naslov) values (2096, 'Rhycero', '33 Kedzie Road');
insert into klub (id, Ime, Naslov) values (2097, 'Divape', '2 Dottie Crossing');
insert into klub (id, Ime, Naslov) values (2098, 'Voolia', '170 Miller Junction');
insert into klub (id, Ime, Naslov) values (2099, 'Skyvu', '99429 Huxley Pass');
insert into klub (id, Ime, Naslov) values (2100, 'Bluezoom', '73 Almo Street');
insert into klub (id, Ime, Naslov) values (2101, 'Zoomcast', '607 Havey Drive');
insert into klub (id, Ime, Naslov) values (2102, 'Feedbug', '166 Stone Corner Terrace');
insert into klub (id, Ime, Naslov) values (2103, 'Chatterpoint', '41 Northridge Parkway');
insert into klub (id, Ime, Naslov) values (2104, 'Riffwire', '16 Reindahl Point');
insert into klub (id, Ime, Naslov) values (2105, 'Tazzy', '53199 Merry Hill');
insert into klub (id, Ime, Naslov) values (2106, 'Twimbo', '3 Ridgeview Trail');
insert into klub (id, Ime, Naslov) values (2107, 'Agivu', '1338 Green Ridge Road');
insert into klub (id, Ime, Naslov) values (2108, 'Rhyzio', '4197 Sunbrook Trail');
insert into klub (id, Ime, Naslov) values (2109, 'Zoombox', '8316 Di Loreto Plaza');
insert into klub (id, Ime, Naslov) values (2110, 'Wikido', '5389 Mcbride Road');
insert into klub (id, Ime, Naslov) values (2111, 'Skibox', '0816 Coolidge Crossing');
insert into klub (id, Ime, Naslov) values (2112, 'Gabspot', '80350 Sheridan Avenue');
insert into klub (id, Ime, Naslov) values (2113, 'Lazz', '5981 Oak Valley Hill');
insert into klub (id, Ime, Naslov) values (2114, 'Skippad', '163 Westend Trail');
insert into klub (id, Ime, Naslov) values (2115, 'Kazio', '43 Killdeer Plaza');
insert into klub (id, Ime, Naslov) values (2116, 'Realpoint', '6655 Loeprich Junction');
insert into klub (id, Ime, Naslov) values (2117, 'Photobug', '5 3rd Crossing');
insert into klub (id, Ime, Naslov) values (2118, 'Skipstorm', '01 South Trail');
insert into klub (id, Ime, Naslov) values (2119, 'Gabcube', '81283 Eggendart Drive');
insert into klub (id, Ime, Naslov) values (2120, 'Yacero', '24 Barnett Court');
insert into klub (id, Ime, Naslov) values (2121, 'Kwilith', '044 Manitowish Street');
insert into klub (id, Ime, Naslov) values (2122, 'Fadeo', '29377 Fordem Road');
insert into klub (id, Ime, Naslov) values (2123, 'Skilith', '52874 Jackson Lane');
insert into klub (id, Ime, Naslov) values (2124, 'Trilith', '8583 Logan Street');
insert into klub (id, Ime, Naslov) values (2125, 'Photospace', '543 Service Plaza');
insert into klub (id, Ime, Naslov) values (2126, 'Linkbuzz', '2404 Oriole Crossing');
insert into klub (id, Ime, Naslov) values (2127, 'Linkbridge', '750 Miller Parkway');
insert into klub (id, Ime, Naslov) values (2128, 'Gabtune', '3982 Kropf Point');
insert into klub (id, Ime, Naslov) values (2129, 'Twitterbridge', '8 Sugar Alley');
insert into klub (id, Ime, Naslov) values (2130, 'Zooveo', '87954 Bayside Street');
insert into klub (id, Ime, Naslov) values (2131, 'Vitz', '84991 Jackson Center');
insert into klub (id, Ime, Naslov) values (2132, 'Voonte', '855 Village Street');
insert into klub (id, Ime, Naslov) values (2133, 'Zoomlounge', '997 Washington Circle');
insert into klub (id, Ime, Naslov) values (2134, 'Jetpulse', '067 Spohn Drive');
insert into klub (id, Ime, Naslov) values (2135, 'Demizz', '84507 Colorado Hill');
insert into klub (id, Ime, Naslov) values (2136, 'Mynte', '3347 Thackeray Hill');
insert into klub (id, Ime, Naslov) values (2137, 'Feedbug', '9 Lillian Circle');
insert into klub (id, Ime, Naslov) values (2138, 'Divape', '549 Swallow Way');
insert into klub (id, Ime, Naslov) values (2139, 'Roodel', '28584 Butternut Junction');
insert into klub (id, Ime, Naslov) values (2140, 'Mybuzz', '81010 Park Meadow Pass');
insert into klub (id, Ime, Naslov) values (2141, 'Oyondu', '6 Derek Plaza');
insert into klub (id, Ime, Naslov) values (2142, 'Dabvine', '810 Erie Circle');
insert into klub (id, Ime, Naslov) values (2143, 'Quimm', '20399 Namekagon Terrace');
insert into klub (id, Ime, Naslov) values (2144, 'Linkbridge', '7 Paget Trail');
insert into klub (id, Ime, Naslov) values (2145, 'Meedoo', '286 Coleman Pass');
insert into klub (id, Ime, Naslov) values (2146, 'Nlounge', '6 Sullivan Crossing');
insert into klub (id, Ime, Naslov) values (2147, 'Voolith', '985 Grover Parkway');
insert into klub (id, Ime, Naslov) values (2148, 'Npath', '4112 Southridge Street');
insert into klub (id, Ime, Naslov) values (2149, 'Meevee', '04 Farragut Terrace');
insert into klub (id, Ime, Naslov) values (2150, 'Realbuzz', '52 Dovetail Point');
insert into klub (id, Ime, Naslov) values (2151, 'Twitterbeat', '62608 Riverside Plaza');
insert into klub (id, Ime, Naslov) values (2152, 'Photobug', '2 Nevada Alley');
insert into klub (id, Ime, Naslov) values (2153, 'Yoveo', '3942 Vahlen Way');
insert into klub (id, Ime, Naslov) values (2154, 'Jetpulse', '0030 Almo Point');
insert into klub (id, Ime, Naslov) values (2155, 'Demimbu', '0809 Springs Court');
insert into klub (id, Ime, Naslov) values (2156, 'Kwideo', '518 Portage Pass');
insert into klub (id, Ime, Naslov) values (2157, 'Topicshots', '85 Maple Crossing');
insert into klub (id, Ime, Naslov) values (2158, 'Twitternation', '7 Bluestem Pass');
insert into klub (id, Ime, Naslov) values (2159, 'Browsetype', '63464 Springs Place');
insert into klub (id, Ime, Naslov) values (2160, 'Gigaclub', '14427 Rieder Center');
insert into klub (id, Ime, Naslov) values (2161, 'Layo', '43 Fairfield Road');
insert into klub (id, Ime, Naslov) values (2162, 'BlogXS', '5985 Loomis Road');
insert into klub (id, Ime, Naslov) values (2163, 'Dabshots', '6234 Talmadge Plaza');
insert into klub (id, Ime, Naslov) values (2164, 'Brainverse', '05256 Prairieview Road');
insert into klub (id, Ime, Naslov) values (2165, 'Devify', '53 Clove Center');
insert into klub (id, Ime, Naslov) values (2166, 'Kazio', '35 Elmside Parkway');
insert into klub (id, Ime, Naslov) values (2167, 'Edgewire', '368 Evergreen Drive');
insert into klub (id, Ime, Naslov) values (2168, 'Eadel', '89 Hauk Circle');
insert into klub (id, Ime, Naslov) values (2169, 'Abata', '35 American Pass');
insert into klub (id, Ime, Naslov) values (2170, 'Flashpoint', '839 Loftsgordon Way');
insert into klub (id, Ime, Naslov) values (2171, 'Topdrive', '141 Stoughton Crossing');
insert into klub (id, Ime, Naslov) values (2172, 'Divanoodle', '66 Oak Valley Parkway');
insert into klub (id, Ime, Naslov) values (2173, 'Bubbletube', '83 Morning Crossing');
insert into klub (id, Ime, Naslov) values (2174, 'Dabvine', '7 Birchwood Place');
insert into klub (id, Ime, Naslov) values (2175, 'Skimia', '3 Cardinal Circle');
insert into klub (id, Ime, Naslov) values (2176, 'Zoonoodle', '070 Arrowood Place');
insert into klub (id, Ime, Naslov) values (2177, 'Agimba', '94 Clyde Gallagher Place');
insert into klub (id, Ime, Naslov) values (2178, 'Plajo', '8432 Tomscot Park');
insert into klub (id, Ime, Naslov) values (2179, 'Flashset', '817 Waubesa Pass');
insert into klub (id, Ime, Naslov) values (2180, 'Oyonder', '0 Northfield Plaza');
insert into klub (id, Ime, Naslov) values (2181, 'Jabbersphere', '25909 Reinke Junction');
insert into klub (id, Ime, Naslov) values (2182, 'Thoughtstorm', '5 Barby Trail');
insert into klub (id, Ime, Naslov) values (2183, 'Wordware', '8277 Northfield Pass');
insert into klub (id, Ime, Naslov) values (2184, 'Jabberstorm', '60427 Loomis Trail');
insert into klub (id, Ime, Naslov) values (2185, 'Linklinks', '5 Blaine Pass');
insert into klub (id, Ime, Naslov) values (2186, 'Ailane', '76 Eagle Crest Hill');
insert into klub (id, Ime, Naslov) values (2187, 'Twitternation', '8 Jenna Street');
insert into klub (id, Ime, Naslov) values (2188, 'Topicstorm', '82964 Village Terrace');
insert into klub (id, Ime, Naslov) values (2189, 'Eamia', '9464 Blackbird Crossing');
insert into klub (id, Ime, Naslov) values (2190, 'Skaboo', '8 Pine View Center');
insert into klub (id, Ime, Naslov) values (2191, 'Zooxo', '62867 David Crossing');
insert into klub (id, Ime, Naslov) values (2192, 'Thoughtbridge', '89262 Bobwhite Trail');
insert into klub (id, Ime, Naslov) values (2193, 'Leenti', '3 Stang Way');
insert into klub (id, Ime, Naslov) values (2194, 'Skyble', '2793 Warbler Junction');
insert into klub (id, Ime, Naslov) values (2195, 'Mycat', '3441 South Park');
insert into klub (id, Ime, Naslov) values (2196, 'Babbleopia', '5 Hoard Plaza');
insert into klub (id, Ime, Naslov) values (2197, 'Browsedrive', '95085 Lake View Center');
insert into klub (id, Ime, Naslov) values (2198, 'Plajo', '51840 Merchant Place');
insert into klub (id, Ime, Naslov) values (2199, 'Zoomzone', '6486 Norway Maple Avenue');
insert into klub (id, Ime, Naslov) values (2200, 'Meembee', '9 Sachtjen Circle');
insert into klub (id, Ime, Naslov) values (2201, 'Babbleopia', '1205 Surrey Pass');
insert into klub (id, Ime, Naslov) values (2202, 'Gabspot', '85 Marcy Circle');
insert into klub (id, Ime, Naslov) values (2203, 'Eayo', '2 Twin Pines Road');
insert into klub (id, Ime, Naslov) values (2204, 'Topicblab', '90468 Hermina Pass');
insert into klub (id, Ime, Naslov) values (2205, 'Gigashots', '4894 Hoard Alley');
insert into klub (id, Ime, Naslov) values (2206, 'Eadel', '143 Aberg Avenue');
insert into klub (id, Ime, Naslov) values (2207, 'Aibox', '59258 Ridgeway Place');
insert into klub (id, Ime, Naslov) values (2208, 'Snaptags', '28911 Briar Crest Avenue');
insert into klub (id, Ime, Naslov) values (2209, 'Blogpad', '7 Blue Bill Park Circle');
insert into klub (id, Ime, Naslov) values (2210, 'Jabberbean', '59 Blue Bill Park Alley');
insert into klub (id, Ime, Naslov) values (2211, 'Quinu', '123 Walton Trail');
insert into klub (id, Ime, Naslov) values (2212, 'Meembee', '42 Fairview Court');
insert into klub (id, Ime, Naslov) values (2213, 'Voomm', '3 Moulton Circle');
insert into klub (id, Ime, Naslov) values (2214, 'Devcast', '30830 Continental Crossing');
insert into klub (id, Ime, Naslov) values (2215, 'Rhynoodle', '7006 La Follette Circle');
insert into klub (id, Ime, Naslov) values (2216, 'Abata', '9360 Thierer Center');
insert into klub (id, Ime, Naslov) values (2217, 'Ozu', '44 Rieder Trail');
insert into klub (id, Ime, Naslov) values (2218, 'Skipstorm', '5 Evergreen Crossing');
insert into klub (id, Ime, Naslov) values (2219, 'Wordtune', '3023 Coolidge Road');
insert into klub (id, Ime, Naslov) values (2220, 'Yodel', '20 Village Street');
insert into klub (id, Ime, Naslov) values (2221, 'Flashspan', '3199 Rigney Crossing');
insert into klub (id, Ime, Naslov) values (2222, 'Mydeo', '877 Mesta Alley');
insert into klub (id, Ime, Naslov) values (2223, 'Flashdog', '5 Mendota Junction');
insert into klub (id, Ime, Naslov) values (2224, 'Yodel', '6416 Montana Alley');
insert into klub (id, Ime, Naslov) values (2225, 'Linkbridge', '68429 Pennsylvania Crossing');
insert into klub (id, Ime, Naslov) values (2226, 'Lajo', '0 Caliangt Alley');
insert into klub (id, Ime, Naslov) values (2227, 'Yabox', '94 Parkside Circle');
insert into klub (id, Ime, Naslov) values (2228, 'Agimba', '30 Vermont Road');
insert into klub (id, Ime, Naslov) values (2229, 'Brainverse', '16 Leroy Lane');
insert into klub (id, Ime, Naslov) values (2230, 'Skynoodle', '9 Little Fleur Court');
insert into klub (id, Ime, Naslov) values (2231, 'Jetpulse', '1624 Roth Center');
insert into klub (id, Ime, Naslov) values (2232, 'Camido', '66 Namekagon Point');
insert into klub (id, Ime, Naslov) values (2233, 'Cogidoo', '0557 Lawn Court');
insert into klub (id, Ime, Naslov) values (2234, 'Skibox', '7 Gale Hill');
insert into klub (id, Ime, Naslov) values (2235, 'Quatz', '49 Lien Hill');
insert into klub (id, Ime, Naslov) values (2236, 'Podcat', '0376 Victoria Point');
insert into klub (id, Ime, Naslov) values (2237, 'Rhyloo', '116 Cascade Parkway');
insert into klub (id, Ime, Naslov) values (2238, 'Flashpoint', '28017 8th Hill');
insert into klub (id, Ime, Naslov) values (2239, 'Eire', '93 Novick Alley');
insert into klub (id, Ime, Naslov) values (2240, 'Ooba', '2 Lake View Plaza');
insert into klub (id, Ime, Naslov) values (2241, 'Leenti', '08795 Alpine Alley');
insert into klub (id, Ime, Naslov) values (2242, 'Quaxo', '55 Porter Hill');
insert into klub (id, Ime, Naslov) values (2243, 'Jatri', '7473 Eliot Terrace');
insert into klub (id, Ime, Naslov) values (2244, 'Zava', '733 Fuller Way');
insert into klub (id, Ime, Naslov) values (2245, 'Skinte', '8274 Meadow Vale Place');
insert into klub (id, Ime, Naslov) values (2246, 'Yakijo', '57 Shopko Park');
insert into klub (id, Ime, Naslov) values (2247, 'Eadel', '6 Hoard Way');
insert into klub (id, Ime, Naslov) values (2248, 'Twitterbeat', '2474 Schiller Way');
insert into klub (id, Ime, Naslov) values (2249, 'Gabtune', '310 Sullivan Trail');
insert into klub (id, Ime, Naslov) values (2250, 'Devcast', '697 Bellgrove Point');
insert into klub (id, Ime, Naslov) values (2251, 'Topiclounge', '081 Anderson Place');
insert into klub (id, Ime, Naslov) values (2252, 'Rhyloo', '635 Almo Junction');
insert into klub (id, Ime, Naslov) values (2253, 'Thoughtstorm', '2284 Hayes Terrace');
insert into klub (id, Ime, Naslov) values (2254, 'Gabspot', '1742 Glacier Hill Parkway');
insert into klub (id, Ime, Naslov) values (2255, 'Vipe', '6 Emmet Circle');
insert into klub (id, Ime, Naslov) values (2256, 'Gigabox', '3562 Nancy Avenue');
insert into klub (id, Ime, Naslov) values (2257, 'Thoughtworks', '0277 Magdeline Crossing');
insert into klub (id, Ime, Naslov) values (2258, 'Katz', '60016 Eastwood Alley');
insert into klub (id, Ime, Naslov) values (2259, 'Dynava', '785 Riverside Point');
insert into klub (id, Ime, Naslov) values (2260, 'Photobug', '807 American Street');
insert into klub (id, Ime, Naslov) values (2261, 'Layo', '15 Scofield Avenue');
insert into klub (id, Ime, Naslov) values (2262, 'Voomm', '816 Tennessee Court');
insert into klub (id, Ime, Naslov) values (2263, 'Livepath', '3 High Crossing Alley');
insert into klub (id, Ime, Naslov) values (2264, 'Brainlounge', '6 Little Fleur Hill');
insert into klub (id, Ime, Naslov) values (2265, 'Jetpulse', '076 Mandrake Point');
insert into klub (id, Ime, Naslov) values (2266, 'Brainlounge', '81 Sutherland Street');
insert into klub (id, Ime, Naslov) values (2267, 'Cogilith', '9 Stang Trail');
insert into klub (id, Ime, Naslov) values (2268, 'Dabvine', '9 Manley Avenue');
insert into klub (id, Ime, Naslov) values (2269, 'Agimba', '7301 Derek Alley');
insert into klub (id, Ime, Naslov) values (2270, 'Kwideo', '1717 Farwell Street');
insert into klub (id, Ime, Naslov) values (2271, 'Eabox', '9961 Dixon Trail');
insert into klub (id, Ime, Naslov) values (2272, 'Fivechat', '86281 Grover Parkway');
insert into klub (id, Ime, Naslov) values (2273, 'Mita', '9029 Hayes Drive');
insert into klub (id, Ime, Naslov) values (2274, 'Devshare', '48 Ruskin Avenue');
insert into klub (id, Ime, Naslov) values (2275, 'Meembee', '4 Novick Junction');
insert into klub (id, Ime, Naslov) values (2276, 'Jetpulse', '891 Loomis Center');
insert into klub (id, Ime, Naslov) values (2277, 'Oloo', '08145 Nova Junction');
insert into klub (id, Ime, Naslov) values (2278, 'Mycat', '9 Pawling Place');
insert into klub (id, Ime, Naslov) values (2279, 'Yodel', '8022 Old Shore Crossing');
insert into klub (id, Ime, Naslov) values (2280, 'Omba', '889 Debs Drive');
insert into klub (id, Ime, Naslov) values (2281, 'Jabbersphere', '94 Rutledge Court');
insert into klub (id, Ime, Naslov) values (2282, 'Thoughtblab', '7 Coolidge Center');
insert into klub (id, Ime, Naslov) values (2283, 'Wikizz', '1145 Walton Place');
insert into klub (id, Ime, Naslov) values (2284, 'Quire', '65 4th Point');
insert into klub (id, Ime, Naslov) values (2285, 'Flashpoint', '07 Sunnyside Lane');
insert into klub (id, Ime, Naslov) values (2286, 'Flashpoint', '198 Mitchell Way');
insert into klub (id, Ime, Naslov) values (2287, 'Latz', '26913 Chinook Way');
insert into klub (id, Ime, Naslov) values (2288, 'Vimbo', '82 Katie Lane');
insert into klub (id, Ime, Naslov) values (2289, 'Avamm', '5 Debra Junction');
insert into klub (id, Ime, Naslov) values (2290, 'Myworks', '8 Granby Lane');
insert into klub (id, Ime, Naslov) values (2291, 'Realmix', '98 Fulton Crossing');
insert into klub (id, Ime, Naslov) values (2292, 'Roodel', '90 Donald Avenue');
insert into klub (id, Ime, Naslov) values (2293, 'Brainverse', '752 Harper Park');
insert into klub (id, Ime, Naslov) values (2294, 'Thoughtbeat', '04 Straubel Plaza');
insert into klub (id, Ime, Naslov) values (2295, 'Topicstorm', '175 Ohio Hill');
insert into klub (id, Ime, Naslov) values (2296, 'Skipfire', '3 Duke Lane');
insert into klub (id, Ime, Naslov) values (2297, 'Zoomcast', '7 Little Fleur Lane');
insert into klub (id, Ime, Naslov) values (2298, 'Livetube', '18 Hoepker Junction');
insert into klub (id, Ime, Naslov) values (2299, 'Tagopia', '6 Nevada Road');
insert into klub (id, Ime, Naslov) values (2300, 'Divanoodle', '114 Fulton Terrace');
insert into klub (id, Ime, Naslov) values (2301, 'Yozio', '76754 Atwood Hill');
insert into klub (id, Ime, Naslov) values (2302, 'Babbleset', '9592 Monica Road');
insert into klub (id, Ime, Naslov) values (2303, 'Tagpad', '2 Southridge Avenue');
insert into klub (id, Ime, Naslov) values (2304, 'Aivee', '93581 Reindahl Road');
insert into klub (id, Ime, Naslov) values (2305, 'Trudeo', '63211 Hooker Hill');
insert into klub (id, Ime, Naslov) values (2306, 'Yoveo', '33 Oakridge Alley');
insert into klub (id, Ime, Naslov) values (2307, 'Flashset', '43198 Chinook Place');
insert into klub (id, Ime, Naslov) values (2308, 'Feedmix', '56 Anderson Place');
insert into klub (id, Ime, Naslov) values (2309, 'Jabbercube', '5 Porter Point');
insert into klub (id, Ime, Naslov) values (2310, 'Zoomdog', '8 Alpine Hill');
insert into klub (id, Ime, Naslov) values (2311, 'Oyoyo', '38636 Monterey Crossing');
insert into klub (id, Ime, Naslov) values (2312, 'Buzzshare', '3605 Forster Circle');
insert into klub (id, Ime, Naslov) values (2313, 'Babblestorm', '93609 Packers Drive');
insert into klub (id, Ime, Naslov) values (2314, 'Oyonder', '1155 Kipling Trail');
insert into klub (id, Ime, Naslov) values (2315, 'Oba', '147 Summit Lane');
insert into klub (id, Ime, Naslov) values (2316, 'Yamia', '17602 Hooker Plaza');
insert into klub (id, Ime, Naslov) values (2317, 'Rooxo', '69990 Westport Center');
insert into klub (id, Ime, Naslov) values (2318, 'Cogilith', '2 Mccormick Circle');
insert into klub (id, Ime, Naslov) values (2319, 'Demizz', '995 Lunder Center');
insert into klub (id, Ime, Naslov) values (2320, 'Fivespan', '90395 Spenser Terrace');
insert into klub (id, Ime, Naslov) values (2321, 'Yodel', '07007 Doe Crossing Pass');
insert into klub (id, Ime, Naslov) values (2322, 'Kare', '48099 Bultman Crossing');
insert into klub (id, Ime, Naslov) values (2323, 'Edgetag', '1737 Cody Parkway');
insert into klub (id, Ime, Naslov) values (2324, 'Thoughtstorm', '87861 Grasskamp Plaza');
insert into klub (id, Ime, Naslov) values (2325, 'Feedspan', '4576 Fairview Avenue');
insert into klub (id, Ime, Naslov) values (2326, 'Kwilith', '888 Pleasure Parkway');
insert into klub (id, Ime, Naslov) values (2327, 'Oyoba', '886 Debs Drive');
insert into klub (id, Ime, Naslov) values (2328, 'Aimbu', '3464 Alpine Junction');
insert into klub (id, Ime, Naslov) values (2329, 'Jabbercube', '3 Scofield Hill');
insert into klub (id, Ime, Naslov) values (2330, 'Jaxbean', '071 Green Ridge Lane');
insert into klub (id, Ime, Naslov) values (2331, 'Trupe', '0444 Saint Paul Trail');
insert into klub (id, Ime, Naslov) values (2332, 'Skipfire', '3255 Judy Circle');
insert into klub (id, Ime, Naslov) values (2333, 'Vimbo', '6922 Logan Terrace');
insert into klub (id, Ime, Naslov) values (2334, 'Eayo', '26 6th Road');
insert into klub (id, Ime, Naslov) values (2335, 'Kaymbo', '150 Eastlawn Plaza');
insert into klub (id, Ime, Naslov) values (2336, 'Kazu', '329 Laurel Junction');
insert into klub (id, Ime, Naslov) values (2337, 'Skyvu', '6020 Derek Pass');
insert into klub (id, Ime, Naslov) values (2338, 'Agimba', '8 Di Loreto Circle');
insert into klub (id, Ime, Naslov) values (2339, 'Realfire', '00097 3rd Avenue');
insert into klub (id, Ime, Naslov) values (2340, 'Centizu', '54185 Shelley Parkway');
insert into klub (id, Ime, Naslov) values (2341, 'Muxo', '093 Esker Plaza');
insert into klub (id, Ime, Naslov) values (2342, 'Riffpath', '166 Starling Point');
insert into klub (id, Ime, Naslov) values (2343, 'Lazzy', '91 Commercial Point');
insert into klub (id, Ime, Naslov) values (2344, 'Topicstorm', '309 Mockingbird Plaza');
insert into klub (id, Ime, Naslov) values (2345, 'Meevee', '27 Merrick Trail');
insert into klub (id, Ime, Naslov) values (2346, 'Riffpedia', '17 Ohio Park');
insert into klub (id, Ime, Naslov) values (2347, 'Browsezoom', '34929 Scofield Plaza');
insert into klub (id, Ime, Naslov) values (2348, 'Edgetag', '75 Hermina Pass');
insert into klub (id, Ime, Naslov) values (2349, 'Dabshots', '578 Reinke Place');
insert into klub (id, Ime, Naslov) values (2350, 'Twitternation', '03 Acker Point');
insert into klub (id, Ime, Naslov) values (2351, 'Twitternation', '34 Rutledge Parkway');
insert into klub (id, Ime, Naslov) values (2352, 'Trudoo', '92670 Shelley Hill');
insert into klub (id, Ime, Naslov) values (2353, 'Myworks', '96641 Tony Lane');
insert into klub (id, Ime, Naslov) values (2354, 'Devpoint', '8030 Del Mar Avenue');
insert into klub (id, Ime, Naslov) values (2355, 'Mybuzz', '4 Fair Oaks Lane');
insert into klub (id, Ime, Naslov) values (2356, 'Eimbee', '49676 Jackson Point');
insert into klub (id, Ime, Naslov) values (2357, 'Photospace', '239 Bultman Terrace');
insert into klub (id, Ime, Naslov) values (2358, 'Ozu', '22518 1st Circle');
insert into klub (id, Ime, Naslov) values (2359, 'Realbuzz', '9 Dwight Junction');
insert into klub (id, Ime, Naslov) values (2360, 'Camimbo', '2 Mifflin Parkway');
insert into klub (id, Ime, Naslov) values (2361, 'Agimba', '6660 Amoth Avenue');
insert into klub (id, Ime, Naslov) values (2362, 'Chatterbridge', '2296 Lawn Avenue');
insert into klub (id, Ime, Naslov) values (2363, 'Brainsphere', '61 Twin Pines Circle');
insert into klub (id, Ime, Naslov) values (2364, 'Myworks', '2 Coolidge Park');
insert into klub (id, Ime, Naslov) values (2365, 'Yakitri', '9 Portage Junction');
insert into klub (id, Ime, Naslov) values (2366, 'Topiczoom', '95 Northfield Center');
insert into klub (id, Ime, Naslov) values (2367, 'Fiveclub', '5 Tomscot Plaza');
insert into klub (id, Ime, Naslov) values (2368, 'Gabtune', '882 Elgar Crossing');
insert into klub (id, Ime, Naslov) values (2369, 'Miboo', '214 Chive Park');
insert into klub (id, Ime, Naslov) values (2370, 'Layo', '2 Basil Circle');
insert into klub (id, Ime, Naslov) values (2371, 'Trilith', '54872 Transport Point');
insert into klub (id, Ime, Naslov) values (2372, 'Kazio', '607 Service Way');
insert into klub (id, Ime, Naslov) values (2373, 'Dazzlesphere', '2 Monument Place');
insert into klub (id, Ime, Naslov) values (2374, 'Photobug', '6913 Northridge Terrace');
insert into klub (id, Ime, Naslov) values (2375, 'Ntags', '3575 Golden Leaf Court');
insert into klub (id, Ime, Naslov) values (2376, 'Gigabox', '16078 Knutson Point');
insert into klub (id, Ime, Naslov) values (2377, 'Gabtune', '2 Fallview Parkway');
insert into klub (id, Ime, Naslov) values (2378, 'Demizz', '53 Fisk Junction');
insert into klub (id, Ime, Naslov) values (2379, 'Yakidoo', '4 2nd Hill');
insert into klub (id, Ime, Naslov) values (2380, 'Twitterworks', '743 2nd Point');
insert into klub (id, Ime, Naslov) values (2381, 'Feedfish', '59 Florence Place');
insert into klub (id, Ime, Naslov) values (2382, 'Jaloo', '0 Drewry Road');
insert into klub (id, Ime, Naslov) values (2383, 'Mudo', '1484 Bonner Park');
insert into klub (id, Ime, Naslov) values (2384, 'Kaymbo', '5 Bunker Hill Avenue');
insert into klub (id, Ime, Naslov) values (2385, 'Abatz', '50 Valley Edge Park');
insert into klub (id, Ime, Naslov) values (2386, 'Avamba', '85 Reindahl Way');
insert into klub (id, Ime, Naslov) values (2387, 'Oyoloo', '97 Burning Wood Pass');
insert into klub (id, Ime, Naslov) values (2388, 'Twinder', '6452 Comanche Crossing');
insert into klub (id, Ime, Naslov) values (2389, 'Rhynoodle', '660 Blackbird Hill');
insert into klub (id, Ime, Naslov) values (2390, 'Mydo', '70 Texas Drive');
insert into klub (id, Ime, Naslov) values (2391, 'Riffwire', '02275 Hagan Trail');
insert into klub (id, Ime, Naslov) values (2392, 'Realbuzz', '58 Golden Leaf Avenue');
insert into klub (id, Ime, Naslov) values (2393, 'Fivebridge', '26 Hansons Terrace');
insert into klub (id, Ime, Naslov) values (2394, 'Wikivu', '493 Cherokee Road');
insert into klub (id, Ime, Naslov) values (2395, 'Zoomcast', '00067 Welch Point');
insert into klub (id, Ime, Naslov) values (2396, 'Kaymbo', '0287 Vahlen Circle');
insert into klub (id, Ime, Naslov) values (2397, 'Brainverse', '5 Dakota Avenue');
insert into klub (id, Ime, Naslov) values (2398, 'Realbuzz', '7 Crownhardt Court');
insert into klub (id, Ime, Naslov) values (2399, 'Plajo', '758 Crescent Oaks Crossing');
insert into klub (id, Ime, Naslov) values (2400, 'Skiptube', '19 Browning Street');
insert into klub (id, Ime, Naslov) values (2401, 'Snaptags', '3996 Pearson Parkway');
insert into klub (id, Ime, Naslov) values (2402, 'Skipfire', '39 6th Drive');
insert into klub (id, Ime, Naslov) values (2403, 'Dynabox', '5156 International Place');
insert into klub (id, Ime, Naslov) values (2404, 'Shufflester', '60 Kingsford Avenue');
insert into klub (id, Ime, Naslov) values (2405, 'Mybuzz', '31491 Knutson Alley');
insert into klub (id, Ime, Naslov) values (2406, 'Brainlounge', '8434 Mallard Place');
insert into klub (id, Ime, Naslov) values (2407, 'Lazzy', '721 Burning Wood Junction');
insert into klub (id, Ime, Naslov) values (2408, 'Miboo', '99 Cardinal Plaza');
insert into klub (id, Ime, Naslov) values (2409, 'Youbridge', '7 Spaight Way');
insert into klub (id, Ime, Naslov) values (2410, 'Oyonder', '4586 Springview Road');
insert into klub (id, Ime, Naslov) values (2411, 'Trunyx', '65033 Northport Place');
insert into klub (id, Ime, Naslov) values (2412, 'Shufflester', '79964 Paget Alley');
insert into klub (id, Ime, Naslov) values (2413, 'Skivee', '67 Di Loreto Hill');
insert into klub (id, Ime, Naslov) values (2414, 'Bubblebox', '50671 Paget Avenue');
insert into klub (id, Ime, Naslov) values (2415, 'Riffwire', '8 Hooker Junction');
insert into klub (id, Ime, Naslov) values (2416, 'Oodoo', '812 Lindbergh Terrace');
insert into klub (id, Ime, Naslov) values (2417, 'Twitternation', '409 West Lane');
insert into klub (id, Ime, Naslov) values (2418, 'Zoonder', '3 School Lane');
insert into klub (id, Ime, Naslov) values (2419, 'Oyope', '63 Rutledge Parkway');
insert into klub (id, Ime, Naslov) values (2420, 'Oba', '260 Canary Junction');
insert into klub (id, Ime, Naslov) values (2421, 'Camimbo', '494 Village Green Place');
insert into klub (id, Ime, Naslov) values (2422, 'Topicshots', '5 Toban Hill');
insert into klub (id, Ime, Naslov) values (2423, 'Skimia', '51 Independence Circle');
insert into klub (id, Ime, Naslov) values (2424, 'Oba', '6402 Carioca Circle');
insert into klub (id, Ime, Naslov) values (2425, 'Voonix', '551 Pepper Wood Place');
insert into klub (id, Ime, Naslov) values (2426, 'Yodel', '679 Sugar Point');
insert into klub (id, Ime, Naslov) values (2427, 'Voolith', '5 Talmadge Crossing');
insert into klub (id, Ime, Naslov) values (2428, 'Cogibox', '1 Comanche Hill');
insert into klub (id, Ime, Naslov) values (2429, 'Shufflester', '82 Moose Place');
insert into klub (id, Ime, Naslov) values (2430, 'Rhyloo', '12195 Old Gate Point');
insert into klub (id, Ime, Naslov) values (2431, 'Innotype', '970 Hollow Ridge Crossing');
insert into klub (id, Ime, Naslov) values (2432, 'Photofeed', '46 Utah Parkway');
insert into klub (id, Ime, Naslov) values (2433, 'Rooxo', '2 Fuller Street');
insert into klub (id, Ime, Naslov) values (2434, 'Gabtune', '0 Annamark Parkway');
insert into klub (id, Ime, Naslov) values (2435, 'Skynoodle', '85782 Armistice Hill');
insert into klub (id, Ime, Naslov) values (2436, 'Eamia', '27253 Ridgeway Place');
insert into klub (id, Ime, Naslov) values (2437, 'Ooba', '85745 Nelson Point');
insert into klub (id, Ime, Naslov) values (2438, 'Meembee', '52494 Brentwood Park');
insert into klub (id, Ime, Naslov) values (2439, 'Skivee', '535 Carioca Road');
insert into klub (id, Ime, Naslov) values (2440, 'Aivee', '23 Mariners Cove Place');
insert into klub (id, Ime, Naslov) values (2441, 'Livetube', '6 Green Ridge Lane');
insert into klub (id, Ime, Naslov) values (2442, 'Kwilith', '7201 Coleman Road');
insert into klub (id, Ime, Naslov) values (2443, 'Blogspan', '40251 Forest Run Road');
insert into klub (id, Ime, Naslov) values (2444, 'Nlounge', '27 Parkside Drive');
insert into klub (id, Ime, Naslov) values (2445, 'Aivee', '26051 Clarendon Alley');
insert into klub (id, Ime, Naslov) values (2446, 'Edgepulse', '7 Columbus Junction');
insert into klub (id, Ime, Naslov) values (2447, 'Skiba', '4 Macpherson Court');
insert into klub (id, Ime, Naslov) values (2448, 'Aivee', '14308 Mendota Hill');
insert into klub (id, Ime, Naslov) values (2449, 'Fivechat', '1 Schiller Terrace');
insert into klub (id, Ime, Naslov) values (2450, 'Aimbo', '613 Atwood Way');
insert into klub (id, Ime, Naslov) values (2451, 'Demimbu', '382 Killdeer Point');
insert into klub (id, Ime, Naslov) values (2452, 'Twinte', '36209 Longview Trail');
insert into klub (id, Ime, Naslov) values (2453, 'Feedfish', '46191 Shopko Way');
insert into klub (id, Ime, Naslov) values (2454, 'Twiyo', '6686 Bay Place');
insert into klub (id, Ime, Naslov) values (2455, 'Devpoint', '1229 Kinsman Parkway');
insert into klub (id, Ime, Naslov) values (2456, 'Oloo', '43515 Sunbrook Way');
insert into klub (id, Ime, Naslov) values (2457, 'Photospace', '32019 International Drive');
insert into klub (id, Ime, Naslov) values (2458, 'Pixonyx', '51777 Florence Plaza');
insert into klub (id, Ime, Naslov) values (2459, 'BlogXS', '1 Hazelcrest Street');
insert into klub (id, Ime, Naslov) values (2460, 'Katz', '983 Pine View Crossing');
insert into klub (id, Ime, Naslov) values (2461, 'Kwinu', '504 Grasskamp Hill');
insert into klub (id, Ime, Naslov) values (2462, 'Leenti', '09 Vidon Circle');
insert into klub (id, Ime, Naslov) values (2463, 'Bluejam', '0488 Lyons Parkway');
insert into klub (id, Ime, Naslov) values (2464, 'Voonyx', '25649 Novick Plaza');
insert into klub (id, Ime, Naslov) values (2465, 'Fivespan', '30656 Straubel Trail');
insert into klub (id, Ime, Naslov) values (2466, 'Gabtune', '44501 Almo Center');
insert into klub (id, Ime, Naslov) values (2467, 'Wikibox', '36736 Dakota Lane');
insert into klub (id, Ime, Naslov) values (2468, 'Voomm', '8807 Declaration Junction');
insert into klub (id, Ime, Naslov) values (2469, 'Leexo', '1 Pennsylvania Way');
insert into klub (id, Ime, Naslov) values (2470, 'Quinu', '728 Elka Park');
insert into klub (id, Ime, Naslov) values (2471, 'Roomm', '774 Buell Court');
insert into klub (id, Ime, Naslov) values (2472, 'Fanoodle', '5 Cardinal Center');
insert into klub (id, Ime, Naslov) values (2473, 'Skaboo', '991 Vera Plaza');
insert into klub (id, Ime, Naslov) values (2474, 'Feedmix', '4313 Lyons Place');
insert into klub (id, Ime, Naslov) values (2475, 'Yoveo', '3 Nancy Place');
insert into klub (id, Ime, Naslov) values (2476, 'Gigabox', '194 Banding Plaza');
insert into klub (id, Ime, Naslov) values (2477, 'Skiptube', '132 Scofield Crossing');
insert into klub (id, Ime, Naslov) values (2478, 'Linklinks', '6573 Caliangt Court');
insert into klub (id, Ime, Naslov) values (2479, 'Camido', '776 Loomis Center');
insert into klub (id, Ime, Naslov) values (2480, 'Rhyloo', '914 Carpenter Street');
insert into klub (id, Ime, Naslov) values (2481, 'Skyvu', '53348 Lien Drive');
insert into klub (id, Ime, Naslov) values (2482, 'Brightbean', '52 Tomscot Center');
insert into klub (id, Ime, Naslov) values (2483, 'Youtags', '9831 Mayfield Trail');
insert into klub (id, Ime, Naslov) values (2484, 'Voolith', '6 Gateway Road');
insert into klub (id, Ime, Naslov) values (2485, 'Blognation', '805 Jackson Point');
insert into klub (id, Ime, Naslov) values (2486, 'Oloo', '61574 Transport Alley');
insert into klub (id, Ime, Naslov) values (2487, 'Jabberstorm', '82 Monica Drive');
insert into klub (id, Ime, Naslov) values (2488, 'Dabvine', '35 Green Plaza');
insert into klub (id, Ime, Naslov) values (2489, 'Realbuzz', '2418 Anzinger Way');
insert into klub (id, Ime, Naslov) values (2490, 'Gevee', '5 Johnson Point');
insert into klub (id, Ime, Naslov) values (2491, 'Ainyx', '92 Manitowish Crossing');
insert into klub (id, Ime, Naslov) values (2492, 'Skajo', '29 Northview Plaza');
insert into klub (id, Ime, Naslov) values (2493, 'Twitterworks', '428 Sundown Park');
insert into klub (id, Ime, Naslov) values (2494, 'Gevee', '78896 Wayridge Point');
insert into klub (id, Ime, Naslov) values (2495, 'Twitterbeat', '53 Sullivan Plaza');
insert into klub (id, Ime, Naslov) values (2496, 'Voolith', '05 Valley Edge Alley');
insert into klub (id, Ime, Naslov) values (2497, 'Jazzy', '8 Sheridan Point');
insert into klub (id, Ime, Naslov) values (2498, 'Plambee', '32 Haas Parkway');
insert into klub (id, Ime, Naslov) values (2499, 'Skyvu', '72449 Pine View Road');
insert into klub (id, Ime, Naslov) values (2500, 'Zoomcast', '32 Blaine Center');
